package com.adobe.aem.modernizer.dashboard;

/** Pages/blocks preview: HTML view, DA-compatible markup, UE authoring instructions. */
final class PreviewPanel {

    private PreviewPanel() {}

    static String pagesMarkup() {
        return ""
                + "<div class=\"card\" style=\"margin-bottom:16px;\">\n"
                + "  <div class=\"card-title\">Page preview</div>\n"
                + "  <p style=\"font-size:0.85rem;color:var(--text-muted);margin-bottom:12px;\">HTML view, Document Authoring (DA) markup, and Universal Editor authoring instructions.</p>\n"
                + "  <div class=\"prev-split\">\n"
                + "    <div class=\"prev-side\"><table id=\"table-pages\"><thead><tr><th>Path</th><th>Title</th><th>Status</th></tr></thead><tbody><tr><td colspan=\"3\">Run a Dry Run to discover pages.</td></tr></tbody></table></div>\n"
                + "    <div class=\"prev-main\">\n"
                + "      <div class=\"block-file-tabs\">\n"
                + "        <button type=\"button\" id=\"pagetab-html\" class=\"block-file-tab active\" onclick=\"switchPagePreview('html')\">HTML view</button>\n"
                + "        <button type=\"button\" id=\"pagetab-da\" class=\"block-file-tab\" onclick=\"switchPagePreview('da')\">DA compatible</button>\n"
                + "        <button type=\"button\" id=\"pagetab-ue\" class=\"block-file-tab\" onclick=\"switchPagePreview('ue')\">UE authoring</button>\n"
                + "      </div>\n"
                + "      <div id=\"page-preview-path\" class=\"prev-path\">Select a page</div>\n"
                + "      <div id=\"page-view-html\" class=\"prev-pane\"></div>\n"
                + "      <div id=\"page-view-da\" class=\"prev-pane\" style=\"display:none;\"></div>\n"
                + "      <div id=\"page-view-ue\" class=\"prev-pane\" style=\"display:none;\"></div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n";
    }

    static String blocksMarkup() {
        return ""
                + "<div class=\"card\" style=\"margin-bottom:16px;\">\n"
                + "  <div class=\"card-title\">Block preview <span id=\"blocks-count-badge\" class=\"block-item-badge\">0</span></div>\n"
                + "  <p style=\"font-size:0.85rem;color:var(--text-muted);margin-bottom:12px;\">HTML demo, DA table markup, and Universal Editor field instructions.</p>\n"
                + "  <div class=\"prev-split\">\n"
                + "    <div class=\"prev-side\" id=\"block-items-container\"><div style=\"padding:12px;color:var(--text-dim);\">Generate blocks to populate.</div></div>\n"
                + "    <div class=\"prev-main\">\n"
                + "      <div class=\"block-file-tabs\">\n"
                + "        <button type=\"button\" id=\"filetab-html\" class=\"block-file-tab active\" onclick=\"switchBlockPreview('html')\">HTML view</button>\n"
                + "        <button type=\"button\" id=\"filetab-da\" class=\"block-file-tab\" onclick=\"switchBlockPreview('da')\">DA compatible</button>\n"
                + "        <button type=\"button\" id=\"filetab-ue\" class=\"block-file-tab\" onclick=\"switchBlockPreview('ue')\">UE authoring</button>\n"
                + "      </div>\n"
                + "      <div id=\"block-file-path\" class=\"prev-path\">blocks/...</div>\n"
                + "      <div id=\"block-view-html\" class=\"prev-pane\"></div>\n"
                + "      <div id=\"block-view-da\" class=\"prev-pane\" style=\"display:none;\"></div>\n"
                + "      <div id=\"block-view-ue\" class=\"prev-pane\" style=\"display:none;\"></div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "<div class=\"card\"><div class=\"card-title\">Component → block mapping</div>\n"
                + "<ul id=\"table-components\" class=\"data-list\"><li class=\"data-list-empty\">Run a Dry Run to classify components.</li></ul></div>\n";
    }

    static String css() {
        return ".prev-split{display:grid;grid-template-columns:minmax(220px,280px) 1fr;gap:14px;align-items:start;}"
                + ".prev-side{max-height:560px;overflow:auto;border:1px solid var(--surface-border);border-radius:8px;background:#0b1120;}"
                + ".prev-main{min-width:0;}"
                + ".prev-path{font-size:0.78rem;color:var(--text-dim);margin:8px 0 10px;font-family:var(--font-mono);word-break:break-all;}"
                + ".prev-pane{background:#f8fafc;color:#0f172a;border-radius:8px;border:1px solid #e2e8f0;min-height:280px;padding:14px;}"
                + ".block-file-tabs{display:flex;flex-wrap:wrap;gap:6px;}"
                + ".block-file-tab{background:#1e293b;border:1px solid #334155;color:#cbd5e1;border-radius:6px;padding:7px 10px;font-size:0.78rem;font-weight:700;cursor:pointer;}"
                + ".block-file-tab.active{background:rgba(56,189,248,0.18);color:#7dd3fc;border-color:#38bdf8;}"
                + ".block-item{padding:10px 12px;border-bottom:1px solid #1e293b;cursor:pointer;}"
                + ".block-item.active{background:rgba(56,189,248,0.12);}"
                + ".ue-guide h3{margin:12px 0 6px;font-size:1rem;}"
                + ".ue-guide ol{margin:0 0 12px 18px;}"
                + ".da-code{white-space:pre-wrap;font-family:ui-monospace,Menlo,monospace;font-size:0.78rem;background:#0f172a;color:#e2e8f0;padding:12px;border-radius:6px;overflow:auto;}"
                + ".da-editor{background:#fff;color:#202124;padding:16px;margin-top:12px;border:1px solid #dadce0;}"
                + ".da-editor h1{font-size:1.6rem;margin:0 0 12px;font-weight:400;}"
                + ".da-editor table{width:100%;border-collapse:collapse;margin:16px 0;background:#fff;}"
                + ".da-editor td{border:1px solid #bdc1c6;padding:8px 10px;font-size:0.9rem;vertical-align:top;}"
                + ".da-editor tr:first-child td{background:#e8eaed;font-weight:700;text-align:center;}";
    }

    static String script() {
        return "<script>\n"
                + "let generatedFiles=[]; let blockFilesMap={}; let activeBlockName=''; let activePagePath=''; let pagePreviewTab='html'; let blockPreviewTab='html';\n"
                + "async function loadPreviewArtifacts(){\n"
                + "  try { generatedFiles = await api('projects/'+currentProjectId+'/files') || []; } catch(e){ generatedFiles=[]; }\n"
                + "  if (!Array.isArray(generatedFiles)) generatedFiles=[];\n"
                + "  indexBlockFiles();\n"
                + "  renderBlockPreviewList();\n"
                + "  if (activePagePath) renderPagePreview();\n"
                + "}\n"
                + "function indexBlockFiles(){\n"
                + "  blockFilesMap={};\n"
                + "  generatedFiles.forEach(function(f){\n"
                + "    if (!f || !f.path || f.path.indexOf('blocks/')!==0) return;\n"
                + "    var parts=f.path.split('/'); if (parts.length<3) return;\n"
                + "    var name=parts[1];\n"
                + "    if (!blockFilesMap[name]) blockFilesMap[name]={name:name, sourcePath:f.sourcePath, files:{}};\n"
                + "    if (f.sourcePath) blockFilesMap[name].sourcePath=f.sourcePath;\n"
                + "    var fn=parts.slice(2).join('/');\n"
                + "    if (fn.endsWith('.js') && fn.indexOf('.')===fn.lastIndexOf('.')) blockFilesMap[name].files.js=f;\n"
                + "    else if (fn.endsWith('.css')) blockFilesMap[name].files.css=f;\n"
                + "    else if (fn.endsWith('.json')) blockFilesMap[name].files.json=f;\n"
                + "    else if (fn.endsWith('.html')) blockFilesMap[name].files.html=f;\n"
                + "    else if (fn.toLowerCase()==='readme.md') blockFilesMap[name].files.readme=f;\n"
                + "  });\n"
                + "}\n"
                + "function renderPagesPreview(pages){\n"
                + "  var tbody=document.querySelector('#table-pages tbody'); if(!tbody) return;\n"
                + "  if (!pages||!pages.length){ tbody.innerHTML='<tr><td colspan=\"3\">No pages discovered yet.</td></tr>'; return; }\n"
                + "  tbody.innerHTML=pages.map(function(p){\n"
                + "    return '<tr data-path=\"'+esc(p.path)+'\" onclick=\"selectPreviewPage(\\''+jsq(p.path)+'\\')\"><td><code>'+esc(p.path)+'</code></td><td>'+esc(p.title||'-')+'</td><td>'+(p.eligible!==false?'ELIGIBLE':'EXCLUDED')+'</td></tr>';\n"
                + "  }).join('');\n"
                + "  if (!activePagePath) selectPreviewPage(pages[0].path);\n"
                + "}\n"
                + "function selectPreviewPage(path){ activePagePath=path; renderPagePreview(); }\n"
                + "function switchPagePreview(tab){ pagePreviewTab=tab; ['html','da','ue'].forEach(function(t){ var b=document.getElementById('pagetab-'+t); if(b) b.classList.toggle('active', t===tab); }); renderPagePreview(); }\n"
                + "function pageFile(){ return generatedFiles.find(function(x){ return x.sourcePath===activePagePath && x.path && x.path.indexOf('docs/migrated-pages/')===0 && x.path.endsWith('.md'); }) || generatedFiles.find(function(x){ return x.fileType==='SECTION_MD' && x.sourcePath===activePagePath; }); }\n"
                + "function pageMarkdown(){ var f=pageFile(); return f? (f.content||'') : ''; }\n"
                + "function renderPagePreview(){\n"
                + "  var pathEl=document.getElementById('page-preview-path');\n"
                + "  var md=pageMarkdown();\n"
                + "  var file=pageFile();\n"
                + "  if (pathEl) pathEl.textContent = file? file.path : (activePagePath||'Select a page');\n"
                + "  showPane('page-view-html', pagePreviewTab==='html');\n"
                + "  showPane('page-view-da', pagePreviewTab==='da');\n"
                + "  showPane('page-view-ue', pagePreviewTab==='ue');\n"
                + "  if (pagePreviewTab==='html') document.getElementById('page-view-html').innerHTML = pageHtmlIframe(md);\n"
                + "  if (pagePreviewTab==='da') document.getElementById('page-view-da').innerHTML = daPageView(md);\n"
                + "  if (pagePreviewTab==='ue') document.getElementById('page-view-ue').innerHTML = uePageGuide(md);\n"
                + "}\n"
                + "function pageHtmlIframe(md){\n"
                + "  var doc = '<!doctype html><html><head><meta charset=utf-8><style>body{font-family:system-ui;margin:20px;color:#334155} table{border-collapse:collapse;width:100%;margin:12px 0} td,th{border:1px solid #cbd5e1;padding:8px}</style></head><body>'+mdToSimpleHtml(md)+'</body></html>';\n"
                + "  return '<iframe srcdoc=\"'+doc.replace(/\"/g,'&quot;')+'\" style=\"width:100%;min-height:420px;border:0;background:#fff;\"></iframe>';\n"
                + "}\n"
                + "function daDocPath(aem){ if(!aem) return '/index'; var p=aem; if(p.indexOf('/content/wknd')===0) p=p.substring(13); else if(p.indexOf('/content/')===0){ var i=p.indexOf('/',9); if(i>0) p=p.substring(i);} return p||'/index'; }\n"
                + "function daPageView(md){\n"
                + "  var title=(md.match(new RegExp('^#\\\\s+(.+)$','m'))||[])[1]||'';\n"
                + "  var stored=generatedFiles.find(function(x){ return x.sourcePath===activePagePath && (x.fileType==='DA_HTML' || (x.path&&x.path.indexOf('docs/migrated-pages')===0 && String(x.path).endsWith('.html'))); });\n"
                + "  var html=(stored&&stored.content)? stored.content : daFromMarkdown(md,title,activePagePath);\n"
                + "  var paste=daPasteInner(html);\n"
                + "  var path=daDocPath(activePagePath);\n"
                + "  window.__daPaste=paste;\n"
                + "  return '<p style=\"font-size:0.82rem;color:#334155;margin:0 0 8px;\">DA document path (matches AEM root after site prefix): <code>'+esc(path)+'</code></p>'"
                + "+'<p style=\"font-size:0.78rem;color:#64748b;margin:0 0 10px;\">Copy the tables below into Document Authoring. The first row of each table is the block name (required). Do not paste the styled preview chrome.</p>'"
                + "+'<button type=\"button\" class=\"btn btn-primary\" onclick=\"copyDaPaste()\">Copy for Document Authoring</button>'"
                + "+'<div class=\"da-editor\">'+daVisualTables(html)+'</div>'"
                + "+'<textarea id=\"da-paste-src\" class=\"da-code\" style=\"width:100%;min-height:180px;margin-top:10px;\">'+esc(paste)+'</text'+'area>';\n"
                + "}\n"
                + "function copyDaPaste(){ var t=window.__daPaste||''; navigator.clipboard.writeText(t).then(function(){ if(typeof showToast==='function') showToast('Copied DA HTML for '+daDocPath(activePagePath)); }); }\n"
                + "function daPasteInner(html){ var m=String(html||'').match(new RegExp('<main>([\\\\s\\\\S]*?)</ma'+'in>','i')); return m? m[1].trim() : html; }\n"
                + "function daFromMarkdown(md,title,aemPath){\n"
                + "  title=title||'Page'; var blocks=parseMdBlocks(md); var inner='<h1>'+esc(title)+'</h1>';\n"
                + "  if(!blocks.length){ inner+='<p>No blocks for this root path. Run Generate on the selected page.</p>'; }\n"
                + "  else { blocks.forEach(function(b){ inner+=daTable(b.name, daRowsFromBlock(b)); }); }\n"
                + "  inner+=daTable('Metadata',[['title',title],['source-path',aemPath||'']]);\n"
                + "  return '<body>\\\\n<header></header>\\\\n<main>\\\\n<div>\\\\n'+inner+'\\\\n</div>\\\\n</main>\\\\n<footer></footer>\\\\n</body>';\n"
                + "}\n"
                + "function daRowsFromBlock(b){ var rows=[]; if(!b.fields||!b.fields.length) return rows; var pair=true; b.fields.forEach(function(f){ if(f.name&&f.value!==undefined) rows.push([f.name,f.value]); else pair=false; }); if(!pair){ rows=[b.fields.map(function(f){return f.value||f.name||'';})]; } return rows; }\n"
                + "function daTable(name,rows){ var w=1; rows.forEach(function(r){ w=Math.max(w,r.length||1); }); var h=name==='Metadata'?'Metadata':name; var s='<table>\\n<tr><td colspan=\"'+w+'\">'+esc(h)+'</td></tr>\\n';\n"
                + "  if(!rows.length) s+='<tr><td></td></tr>\\n';\n"
                + "  rows.forEach(function(r){ s+='<tr>'; for(var i=0;i<w;i++){ var c=r[i]||''; s+='<td>'+(looksImg(c)?'<img src=\"'+esc(c)+'\" alt=\"\">':esc(c))+'</td>'; } s+='</tr>\\n'; });\n"
                + "  return s+'</table>\\n';\n"
                + "}\n"
                + "function looksImg(c){ c=String(c||'').toLowerCase(); return c.indexOf('/content/dam/')===0||new RegExp('\\\\.(png|jpe?g|gif|webp|svg)$').test(c); }\n"
                + "function daVisualTables(html){ var m=String(html||'').match(new RegExp('<main>([\\\\s\\\\S]*?)</ma'+'in>','i')); return m? m[1] : html; }\n"
                + "function uePageGuide(md){\n"
                + "  var blocks=parseMdBlocks(md);\n"
                + "  var html='<div class=\"ue-guide\"><h3>Author this page in Universal Editor</h3><ol>'"
                + "+'<li>Open the migrated page in AEM Universal Editor (authoring strategy UNIVERSAL_EDITOR).</li>'"
                + "+'<li>Keep the JCR source <code>'+esc(activePagePath||'')+'</code>.</li>'"
                + "+'<li>Add each block from the component palette. Field names below match <code>component-models.json</code> / <code>_<block>.json</code>.</li>'"
                + "+'<li>Do not edit fstab.yaml. Page markdown lives under <code>docs/migrated-pages/</code>.</li></ol>';\n"
                + "  if (!blocks.length) html+='<p>Generate the site to produce block tables for this page.</p>';\n"
                + "  blocks.forEach(function(b){ html+='<h3>Block: '+esc(b.name)+'</h3><table><thead><tr><th>Field</th><th>UE component</th><th>Sample</th></tr></thead><tbody>';\n"
                + "    b.fields.forEach(function(f){ html+='<tr><td><code>'+esc(f.name)+'</code></td><td>'+esc(ueFieldType(f.name))+'</td><td>'+esc(f.value)+'</td></tr>'; });\n"
                + "    html+='</tbody></table>'; });\n"
                + "  return html+'</div>';\n"
                + "}\n"
                + "function renderBlockPreviewList(){\n"
                + "  var c=document.getElementById('block-items-container'); var names=Object.keys(blockFilesMap);\n"
                + "  var badge=document.getElementById('blocks-count-badge'); if(badge) badge.textContent=names.length+' blocks';\n"
                + "  if(!c) return;\n"
                + "  if(!names.length){ c.innerHTML='<div style=\"padding:12px;color:#94a3b8;\">Generate blocks to populate.</div>'; return; }\n"
                + "  if(!activeBlockName||!blockFilesMap[activeBlockName]) activeBlockName=names[0];\n"
                + "  c.innerHTML=names.map(function(n){ return '<div class=\"block-item '+(n===activeBlockName?'active':'')+'\" onclick=\"selectPreviewBlock(\\''+jsq(n)+'\\')\">🧱 '+esc(n)+'</div>'; }).join('');\n"
                + "  renderBlockPreview();\n"
                + "}\n"
                + "function selectPreviewBlock(n){ activeBlockName=n; renderBlockPreviewList(); }\n"
                + "function switchBlockPreview(tab){ blockPreviewTab=tab; ['html','da','ue'].forEach(function(t){ var b=document.getElementById('filetab-'+t); if(b) b.classList.toggle('active', t===tab); }); renderBlockPreview(); }\n"
                + "function renderBlockPreview(){\n"
                + "  var b=blockFilesMap[activeBlockName]; if(!b) return;\n"
                + "  var path=document.getElementById('block-file-path'); if(path) path.textContent='blocks/'+activeBlockName+'/';\n"
                + "  showPane('block-view-html', blockPreviewTab==='html');\n"
                + "  showPane('block-view-da', blockPreviewTab==='da');\n"
                + "  showPane('block-view-ue', blockPreviewTab==='ue');\n"
                + "  var html=(b.files.html&&b.files.html.content)||'';\n"
                + "  if (blockPreviewTab==='html') document.getElementById('block-view-html').innerHTML = html ? ('<iframe srcdoc=\"'+html.replace(/\"/g,'&quot;')+'\" style=\"width:100%;min-height:420px;border:0;\"></iframe>') : '<p>No example HTML yet. Generate blocks.</p>';\n"
                + "  if (blockPreviewTab==='da') document.getElementById('block-view-da').innerHTML = blockDaView(b);\n"
                + "  if (blockPreviewTab==='ue') document.getElementById('block-view-ue').innerHTML = blockUeView(b);\n"
                + "}\n"
                + "function blockDaView(b){\n"
                + "  var src=blockToDaHtml(b);\n"
                + "  window.__daPaste=src.source;\n"
                + "  return '<p style=\"font-size:0.82rem;color:#334155;\">Paste this table into DA. First row is the block name.</p>'"
                + "+'<button type=\"button\" class=\"btn btn-primary\" onclick=\"copyDaPaste()\">Copy for Document Authoring</button>'"
                + "+'<div class=\"da-editor\">'+src.preview+'</div><textarea class=\"da-code\" style=\"width:100%;min-height:140px;margin-top:10px;\">'+esc(src.source)+'</text'+'area>';\n"
                + "}\n"
                + "function blockUeView(b){\n"
                + "  var fields=ueFieldsFromJson(b.files.json && b.files.json.content);\n"
                + "  var html='<div class=\"ue-guide\"><h3>Author <code>'+esc(b.name)+'</code> in Universal Editor</h3><ol>'"
                + "+'<li>Register this block in <code>component-definition.json</code> (already generated as <code>_'+esc(b.name)+'.json</code>).</li>'"
                + "+'<li>In UE, insert the block from the palette onto the section.</li>'"
                + "+'<li>Fill the property panel fields below. Images use <code>reference</code>, links use <code>aem-content</code>.</li></ol>';\n"
                + "  if (fields.length){ html+='<table><thead><tr><th>Field</th><th>Component</th></tr></thead><tbody>';\n"
                + "    fields.forEach(function(f){ html+='<tr><td><code>'+esc(f.name)+'</code></td><td>'+esc(f.component||ueFieldType(f.name))+'</td></tr>'; }); html+='</tbody></table>'; }\n"
                + "  else html+='<p>No UE model JSON yet. Generate blocks to create <code>_'+esc(b.name)+'.json</code>.</p>';\n"
                + "  if (b.files.readme) html+='<h3>README</h3><pre class=\"da-code\">'+esc(b.files.readme.content||'')+'</pre>';\n"
                + "  return html+'</div>';\n"
                + "}\n"
                + "function blockToDaHtml(b){\n"
                + "  var fields=ueFieldsFromJson(b.files&&b.files.json&&b.files.json.content);\n"
                + "  var rows=fields.map(function(f){return [f.name,''];});\n"
                + "  var src=daTable(b.name, rows);\n"
                + "  return {preview:src, source:src};\n"
                + "}\n"
                + "function mdToDaHtml(md){\n"
                + "  var blocks=parseMdBlocks(md); var body='<header></header><main><div>';\n"
                + "  var preview='';\n"
                + "  if (!blocks.length){ var simple=mdToSimpleHtml(md); return {preview:simple, source:'<body><header></header><main><div>'+stripTagsKeepText(md)+'</div></main><footer></footer></body>'}; }\n"
                + "  blocks.forEach(function(b){\n"
                + "    var cls=b.name.toLowerCase().replace(/[^a-z0-9-]+/g,'-');\n"
                + "    body+='<div class=\"'+cls+'\">'; preview+='<div style=\"border:2px solid #2563eb;margin:10px 0;\"><div style=\"background:#dbeafe;padding:6px 10px;font-weight:700;\">'+esc(cls)+'</div>';\n"
                + "    body+='<div>'; preview+='<table style=\"width:100%;border-collapse:collapse;\">';\n"
                + "    b.fields.forEach(function(f){ body+='<div>'+esc(f.value)+'</div>'; preview+='<tr><td style=\"border:1px solid #93c5fd;padding:6px;\">'+esc(f.value)+'</td></tr>'; });\n"
                + "    body+='</div></div>'; preview+='</table></div>';\n"
                + "  });\n"
                + "  body+='</div></main><footer></footer>';\n"
                + "  return {preview:preview, source:'<body>'+body+'</body>'};\n"
                + "}\n"
                + "function parseMdBlocks(md){\n"
                + "  var blocks=[]; if(!md) return blocks; var lines=md.split(/\\n/); var cur=null; var headers=[];\n"
                + "  lines.forEach(function(raw){ var line=raw.trim();\n"
                + "    if (line.indexOf('### ')===0){ cur={name:line.substring(4).trim(), fields:[]}; blocks.push(cur); headers=[]; return; }\n"
                + "    if (!cur || line.indexOf('|')!==0) return;\n"
                + "    var cols=line.split('|').map(function(c){return c.trim();}).filter(function(c,i,a){return i>0 && i<a.length-1;});\n"
                + "    if (cols.every(function(c){ return /^-/.test(c); })) return;\n"
                + "    if (!headers.length){ headers=cols; return; }\n"
                + "    cols.forEach(function(val,i){ cur.fields.push({name:headers[i]||('col'+(i+1)), value:val}); });\n"
                + "  }); return blocks;\n"
                + "}\n"
                + "function mdToSimpleHtml(md){\n"
                + "  if(!md) return '<p>No migrated markdown. Run Generate.</p>';\n"
                + "  return md.split(/\\n/).map(function(l){ l=l.trim();\n"
                + "    if(l.indexOf('# ')===0) return '<h1>'+esc(l.substring(2))+'</h1>';\n"
                + "    if(l.indexOf('## ')===0) return '<h2>'+esc(l.substring(3))+'</h2>';\n"
                + "    if(l.indexOf('### ')===0) return '<h3>'+esc(l.substring(4))+'</h3>';\n"
                + "    if(l.indexOf('|')===0) return '<p>'+esc(l)+'</p>';\n"
                + "    return l? '<p>'+esc(l)+'</p>' : '';\n"
                + "  }).join('');\n"
                + "}\n"
                + "function ueFieldsFromJson(raw){\n"
                + "  if(!raw) return []; try { var j=JSON.parse(raw); var models=j.models||j; if(!Array.isArray(models)) models=models?[models]:[];\n"
                + "    var fields=[]; models.forEach(function(m){ (m.fields||[]).forEach(function(f){ fields.push({name:f.name||f.id||'', component:f.component||''}); }); }); return fields;\n"
                + "  } catch(e){ return []; }\n"
                + "}\n"
                + "function ueFieldType(name){ name=String(name||'').toLowerCase(); if(name.indexOf('image')>=0||name.indexOf('file')>=0) return 'reference'; if(name.indexOf('link')>=0||name.indexOf('url')>=0||name.indexOf('path')>=0) return 'aem-content'; if(name.indexOf('text')>=0||name.indexOf('title')>=0||name.indexOf('desc')>=0) return 'richtext'; return 'text'; }\n"
                + "function showPane(id,on){ var el=document.getElementById(id); if(el) el.style.display=on?'block':'none'; }\n"
                + "function esc(s){ return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }\n"
                + "function jsq(s){ return String(s||'').replace(/\\\\/g,'\\\\\\\\').replace(/'/g,\"\\\\'\"); }\n"
                + "function stripTagsKeepText(md){ return esc(md||''); }\n"
                + "</script>\n";
    }
}