package com.adobe.aem.modernizer.dashboard;

/**
 * Generates the self-contained, inlined Modernizer Dashboard SPA (Master §3, §31, ADR 0002).
 * Provides a publish-style control center with interactive project configuration and migration controls.
 */
public final class StaticDashboard {

    private StaticDashboard() {}

    public static String html() {
        return html("/bin/aem-eds-modernizer/api");
    }

    public static String html(String apiBase) {
        String base = (apiBase == null || apiBase.trim().isEmpty())
                ? "/bin/aem-eds-modernizer/api" : apiBase.trim();
        if (!base.endsWith("/")) {
            base += "/";
        }

        return "<!doctype html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <title>AEM → EDS Modernizer</title>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
                + "  <base href=\"" + base + "\">\n"
                + "  <style>\n"
                + "    :root {\n"
                + "      --bg-dark: #090d16;\n"
                + "      --bg-header: rgba(15, 23, 42, 0.9);\n"
                + "      --surface: #131d31;\n"
                + "      --surface-card: #1e293b;\n"
                + "      --surface-border: #334155;\n"
                + "      --surface-focus: #475569;\n"
                + "      --primary: #38bdf8;\n"
                + "      --primary-hover: #0ea5e9;\n"
                + "      --accent: #10b981;\n"
                + "      --accent-hover: #059669;\n"
                + "      --warn: #f59e0b;\n"
                + "      --danger: #ef4444;\n"
                + "      --purple: #a855f7;\n"
                + "      --text: #f8fafc;\n"
                + "      --text-muted: #94a3b8;\n"
                + "      --text-dim: #64748b;\n"
                + "      --font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;\n"
                + "      --font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;\n"
                + "    }\n"
                + "    * { box-sizing: border-box; margin: 0; padding: 0; }\n"
                + "    body { background: var(--bg-dark); color: var(--text); font-family: var(--font-sans); min-height: 100vh; display: flex; flex-direction: column; }\n"
                + "    header { background: var(--bg-header); backdrop-filter: blur(12px); border-bottom: 1px solid var(--surface-border); padding: 14px 28px; display: flex; justify-content: space-between; align-items: center; position: sticky; top: 0; z-index: 100; gap: 16px; flex-wrap: wrap; }\n"
                + "    .brand { display: flex; align-items: center; gap: 12px; font-size: 1.25rem; font-weight: 700; color: var(--text); text-decoration: none; }\n"
                + "    .brand svg { fill: var(--primary); }\n"
                + "    .header-center { display: flex; align-items: center; gap: 12px; }\n"
                + "    .project-selector { background: var(--surface-card); border: 1px solid var(--surface-border); color: var(--text); padding: 7px 14px; border-radius: 6px; font-size: 0.85rem; font-weight: 600; cursor: pointer; outline: none; }\n"
                + "    .header-right { display: flex; align-items: center; gap: 10px; }\n"
                + "    .status-badge { display: inline-flex; align-items: center; gap: 6px; padding: 5px 12px; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; background: rgba(16,185,129,0.15); color: var(--accent); border: 1px solid rgba(16,185,129,0.3); }\n"
                + "    .container { max-width: 1440px; margin: 0 auto; padding: 24px 28px; width: 100%; flex: 1; }\n"
                + "    .nav-tabs { display: flex; gap: 6px; border-bottom: 1px solid var(--surface-border); margin-bottom: 24px; overflow-x: auto; }\n"
                + "    .nav-tab { padding: 10px 18px; border: none; background: transparent; color: var(--text-muted); font-size: 0.88rem; font-weight: 600; cursor: pointer; border-bottom: 2px solid transparent; transition: all 0.2s; white-space: nowrap; border-radius: 6px 6px 0 0; }\n"
                + "    .nav-tab:hover { color: var(--text); background: rgba(255,255,255,0.03); }\n"
                + "    .nav-tab.active { color: var(--primary); border-bottom-color: var(--primary); background: rgba(56,189,248,0.08); }\n"
                + "    .actions { display: flex; gap: 10px; margin-bottom: 24px; flex-wrap: wrap; align-items: center; justify-content: space-between; }\n"
                + "    .actions-left, .actions-right { display: flex; gap: 10px; flex-wrap: wrap; align-items: center; }\n"
                + "    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 16px; margin-bottom: 24px; }\n"
                + "    .card { background: var(--surface); border: 1px solid var(--surface-border); border-radius: 10px; padding: 22px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.2); position: relative; }\n"
                + "    .card-title { font-size: 0.82rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted); margin-bottom: 10px; display: flex; justify-content: space-between; align-items: center; }\n"
                + "    .card-val { font-size: 1.9rem; font-weight: 800; color: var(--text); }\n"
                + "    .card-sub { font-size: 0.8rem; color: var(--text-muted); margin-top: 6px; }\n"
                + "    .btn { display: inline-flex; align-items: center; justify-content: center; gap: 8px; padding: 9px 18px; border-radius: 7px; font-weight: 600; font-size: 0.88rem; cursor: pointer; border: none; transition: all 0.2s; text-decoration: none; }\n"
                + "    .btn-primary { background: var(--primary); color: #090d16; }\n"
                + "    .btn-primary:hover { background: var(--primary-hover); transform: translateY(-1px); }\n"
                + "    .btn-accent { background: var(--accent); color: #090d16; }\n"
                + "    .btn-accent:hover { background: var(--accent-hover); transform: translateY(-1px); }\n"
                + "    .btn-outline { background: transparent; border: 1px solid var(--surface-border); color: var(--text); }\n"
                + "    .btn-outline:hover { background: var(--surface-card); border-color: var(--surface-focus); }\n"
                + "    .btn-warn { background: var(--warn); color: #090d16; }\n"
                + "    .btn:disabled { opacity: 0.45; cursor: not-allowed; transform: none !important; }\n"
                + "    .form-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 20px; }\n"
                + "    .form-section { background: var(--surface-card); border: 1px solid var(--surface-border); border-radius: 8px; padding: 20px; }\n"
                + "    .form-section-title { font-size: 0.95rem; font-weight: 700; color: var(--primary); margin-bottom: 16px; border-bottom: 1px solid rgba(255,255,255,0.06); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; }\n"
                + "    .form-group { margin-bottom: 14px; }\n"
                + "    .form-label { display: block; font-size: 0.8rem; font-weight: 600; color: var(--text-muted); margin-bottom: 6px; }\n"
                + "    .form-control { width: 100%; background: #0b1120; border: 1px solid var(--surface-border); border-radius: 6px; padding: 9px 12px; color: var(--text); font-size: 0.88rem; font-family: var(--font-sans); transition: border-color 0.2s; outline: none; }\n"
                + "    .form-control:focus { border-color: var(--primary); box-shadow: 0 0 0 2px rgba(56,189,248,0.2); }\n"
                + "    .form-hint { font-size: 0.75rem; color: var(--text-dim); margin-top: 4px; }\n"
                + "    .pipeline-stepper { display: flex; gap: 4px; margin-bottom: 24px; background: var(--surface-card); border: 1px solid var(--surface-border); border-radius: 8px; padding: 8px; overflow-x: auto; }\n"
                + "    .step-item { flex: 1; min-width: 130px; text-align: center; padding: 8px 12px; border-radius: 6px; font-size: 0.78rem; font-weight: 700; color: var(--text-muted); background: transparent; transition: all 0.2s; }\n"
                + "    .step-item.active { background: rgba(56,189,248,0.15); color: var(--primary); border: 1px solid rgba(56,189,248,0.3); }\n"
                + "    .step-item.done { background: rgba(16,185,129,0.12); color: var(--accent); }\n"
                + "    table { width: 100%; border-collapse: collapse; text-align: left; font-size: 0.875rem; }\n"
                + "    th, td { padding: 12px 16px; border-bottom: 1px solid var(--surface-border); }\n"
                + "    th { color: var(--text-muted); font-weight: 600; background: rgba(15,23,42,0.6); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.04em; }\n"
                + "    tr:hover td { background: rgba(255,255,255,0.02); }\n"
                + "    .log-terminal { background: #060911; border: 1px solid var(--surface-border); border-radius: 8px; padding: 16px; font-family: var(--font-mono); font-size: 0.82rem; height: 360px; overflow-y: auto; color: #a5b4fc; box-shadow: inset 0 2px 4px rgba(0,0,0,0.4); }\n"
                + "    .log-line { margin-bottom: 5px; line-height: 1.5; word-break: break-all; }\n"
                + "    .log-time { color: var(--text-dim); margin-right: 8px; }\n"
                + "    .log-agent { color: var(--primary); font-weight: 700; margin-right: 8px; }\n"
                + "    .toast { position: fixed; bottom: 24px; right: 24px; background: var(--surface-card); border: 1px solid var(--surface-border); color: var(--text); padding: 14px 20px; border-radius: 8px; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.5); z-index: 1000; font-size: 0.9rem; display: none; }\n"
                + "    .toast.show { display: block; animation: slideIn 0.3s ease; }\n"
                + "    @keyframes slideIn { from { transform: translateY(20px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "  <header>\n"
                + "    <a class=\"brand\" href=\"#\">\n"
                + "      <svg width=\"26\" height=\"26\" viewBox=\"0 0 24 24\"><path d=\"M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5\"/></svg>\n"
                + "      <span>AEM → EDS Modernizer</span>\n"
                + "    </a>\n"
                + "    <div class=\"header-center\">\n"
                + "      <label style=\"font-size:0.8rem; color:var(--text-muted); font-weight:600;\">Active Project:</label>\n"
                + "      <select id=\"project-select\" class=\"project-selector\" onchange=\"onProjectSelectChange()\">\n"
                + "        <option value=\"wknd-site\">WKND Site Modernization</option>\n"
                + "        <option value=\"new\">+ Create New Project...</option>\n"
                + "      </select>\n"
                + "    </div>\n"
                + "    <div class=\"header-right\">\n"
                + "      <div id=\"system-status\" class=\"status-badge\">● Ready</div>\n"
                + "    </div>\n"
                + "  </header>\n"
                + "\n"
                + "  <div class=\"container\">\n"
                + "    <div class=\"actions\">\n"
                + "      <div class=\"actions-left\">\n"
                + "        <button class=\"btn btn-outline\" onclick=\"showTab('setup')\">⚙️ Project Configuration</button>\n"
                + "        <button id=\"btn-dryrun\" class=\"btn btn-primary\" onclick=\"runDryRun()\">🔍 Run Dry Run</button>\n"
                + "        <button id=\"btn-migrate\" class=\"btn btn-accent\" onclick=\"runMigration()\" disabled>🚀 Approve Contract & Migrate</button>\n"
                + "      </div>\n"
                + "      <div class=\"actions-right\">\n"
                + "        <button class=\"btn btn-outline\" onclick=\"refreshDashboard()\">🔄 Refresh</button>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Pipeline Stepper -->\n"
                + "    <div class=\"pipeline-stepper\">\n"
                + "      <div id=\"step-connect\" class=\"step-item active\">1. CONNECT</div>\n"
                + "      <div id=\"step-dryrun\" class=\"step-item\">2. DRY RUN</div>\n"
                + "      <div id=\"step-analyze\" class=\"step-item\">3. DISCOVER & ESTIMATE</div>\n"
                + "      <div id=\"step-contract\" class=\"step-item\">4. SIGN CONTRACT</div>\n"
                + "      <div id=\"step-migrate\" class=\"step-item\">5. MIGRATE & AUTHOR</div>\n"
                + "      <div id=\"step-verify\" class=\"step-item\">6. VERIFY & ROLLOUT</div>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"nav-tabs\">\n"
                + "      <button class=\"nav-tab active\" onclick=\"showTab('overview')\">Overview</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('setup')\">Project Setup & Details</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('pages')\">Pages & Scope</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('components')\">Components & Blocks</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('estimate')\">Estimate & Cost</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('redirects')\">301 Redirects</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('dependencies')\">Dependencies Graph</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('rollout')\">Rollout Stages</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('repairs')\">Self-Repair Log</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('benchmarks')\">Benchmarks</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('events')\">Live Events Stream</button>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Overview -->\n"
                + "    <div id=\"tab-overview\" class=\"tab-content\">\n"
                + "      <div class=\"grid\">\n"
                + "        <div class=\"card\"><div class=\"card-title\">Total Pages Discovered</div><div class=\"card-val\" id=\"stat-pages\">0</div><div class=\"card-sub\" id=\"stat-eligible\">0 in migration scope</div></div>\n"
                + "        <div class=\"card\"><div class=\"card-title\">Components Mapped</div><div class=\"card-val\" id=\"stat-components\">0</div><div class=\"card-sub\">Mapped to Edge Delivery blocks</div></div>\n"
                + "        <div class=\"card\"><div class=\"card-title\">Expected AI Cost</div><div class=\"card-val\" id=\"stat-cost\">$0.00</div><div class=\"card-sub\" id=\"stat-requests\">0 AI calls estimated</div></div>\n"
                + "        <div class=\"card\"><div class=\"card-title\">Estimated Duration</div><div class=\"card-val\" id=\"stat-time\">0s</div><div class=\"card-sub\" id=\"stat-range\">Lo: 0s | Hi: 0s</div></div>\n"
                + "      </div>\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Real-time Activity Stream</div>\n"
                + "        <div id=\"terminal\" class=\"log-terminal\">AEM → EDS Modernizer ready. Configure your project or run a Dry Run.</div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Project Setup & Details Form -->\n"
                + "    <div id=\"tab-setup\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\" style=\"margin-bottom: 20px;\">\n"
                + "        <div class=\"card-title\">Modernizer Project & Connection Configuration</div>\n"
                + "        <p style=\"font-size:0.85rem; color:var(--text-muted); margin-bottom:20px;\">\n"
                + "          Configure your source AEM environment, content scope, Edge Delivery Services Git repository, AI model, and migration safety bounds.\n"
                + "        </p>\n"
                + "        <div class=\"form-grid\">\n"
                + "          <!-- Section 1: AEM Connection -->\n"
                + "          <div class=\"form-section\">\n"
                + "            <div class=\"form-section-title\">🌐 AEM Environment & Scope</div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Project ID</label>\n"
                + "              <input type=\"text\" id=\"cfg-id\" class=\"form-control\" value=\"wknd-site\" placeholder=\"e.g. wknd-site\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Project Name</label>\n"
                + "              <input type=\"text\" id=\"cfg-name\" class=\"form-control\" value=\"WKND Site Modernization\" placeholder=\"e.g. WKND Site Modernization\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">AEM Author URL (Cloud or Local)</label>\n"
                + "              <input type=\"text\" id=\"cfg-authorUrl\" class=\"form-control\" value=\"http://localhost:4502\" placeholder=\"https://author-pXXXXX-eYYYYY.adobeaemcloud.com or http://localhost:4502\">\n"
                + "              <div class=\"form-hint\">Secure OSGi connection via modernizer-service principal</div>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">AEM Publish URL (Optional)</label>\n"
                + "              <input type=\"text\" id=\"cfg-publishUrl\" class=\"form-control\" value=\"http://localhost:4503\" placeholder=\"https://publish-pXXXXX-eYYYYY.adobeaemcloud.com\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Content Root Path</label>\n"
                + "              <input type=\"text\" id=\"cfg-contentRoot\" class=\"form-control\" value=\"/content/wknd\" placeholder=\"/content/wknd\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Page / Subtree Scope (Optional)</label>\n"
                + "              <input type=\"text\" id=\"cfg-pageScope\" class=\"form-control\" value=\"/content/wknd/*\" placeholder=\"/content/wknd/us/en or /content/wknd/*\">\n"
                + "            </div>\n"
                + "          </div>\n"
                + "\n"
                + "          <!-- Section 2: Target EDS & Figma -->\n"
                + "          <div class=\"form-section\">\n"
                + "            <div class=\"form-section-title\">🚀 Target EDS & Design</div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">EDS Git Repository URL</label>\n"
                + "              <input type=\"text\" id=\"cfg-repoUrl\" class=\"form-control\" value=\"https://github.com/my-org/wknd-eds\" placeholder=\"https://github.com/my-org/my-eds-repo\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Target Git Branch</label>\n"
                + "              <input type=\"text\" id=\"cfg-branch\" class=\"form-control\" value=\"main\" placeholder=\"main\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Figma Design File URL (Optional)</label>\n"
                + "              <input type=\"text\" id=\"cfg-figmaUrl\" class=\"form-control\" value=\"\" placeholder=\"https://www.figma.com/file/...\">\n"
                + "              <div class=\"form-hint\">Used for visual token extraction & block styling</div>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Authoring Strategy</label>\n"
                + "              <select id=\"cfg-authoringStrategy\" class=\"form-control\">\n"
                + "                <option value=\"UNIVERSAL_EDITOR\" selected>Universal Editor (AEM Author)</option>\n"
                + "                <option value=\"DOCUMENT_AUTHORING\">Document-based (Google Drive / SharePoint)</option>\n"
                + "                <option value=\"HYBRID\">Hybrid Multi-Authoring</option>\n"
                + "              </select>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Marker Opt-in Property</label>\n"
                + "              <input type=\"text\" id=\"cfg-markerProp\" class=\"form-control\" value=\"edsModernize\" placeholder=\"edsModernize\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Marker Expected Value</label>\n"
                + "              <input type=\"text\" id=\"cfg-markerVal\" class=\"form-control\" value=\"true\" placeholder=\"true or *\">\n"
                + "            </div>\n"
                + "          </div>\n"
                + "\n"
                + "          <!-- Section 3: AI Engine & Safety Bounds -->\n"
                + "          <div class=\"form-section\">\n"
                + "            <div class=\"form-section-title\">🤖 AI Intelligence & Safety Limits</div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">AI Provider Preference</label>\n"
                + "              <select id=\"cfg-aiProvider\" class=\"form-control\" onchange=\"onProviderChange()\">\n"
                + "                <option value=\"anthropic\" selected>Anthropic Claude (Recommended)</option>\n"
                + "                <option value=\"openai\">OpenAI (GPT-4o)</option>\n"
                + "                <option value=\"gemini\">Google Gemini (1.5 Pro)</option>\n"
                + "                <option value=\"ollama\">Ollama (Local / Offline)</option>\n"
                + "              </select>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Target AI Model</label>\n"
                + "              <input type=\"text\" id=\"cfg-aiModel\" class=\"form-control\" value=\"claude-3-5-sonnet-20241022\" placeholder=\"model identifier\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Max AI Budget Limit (USD)</label>\n"
                + "              <input type=\"number\" id=\"cfg-maxBudget\" class=\"form-control\" value=\"100.00\" step=\"10\">\n"
                + "              <div class=\"form-hint\">Hard ceiling to prevent unexpected API spending</div>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Max Self-Repair Attempts (Bounded Loop)</label>\n"
                + "              <input type=\"number\" id=\"cfg-maxRepair\" class=\"form-control\" value=\"5\" min=\"1\" max=\"10\">\n"
                + "            </div>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "\n"
                + "        <div style=\"margin-top:24px; display:flex; gap:12px; flex-wrap:wrap;\">\n"
                + "          <button class=\"btn btn-primary\" onclick=\"saveProjectConfig()\">💾 Save & Connect Project</button>\n"
                + "          <button class=\"btn btn-outline\" onclick=\"loadWkndPreset()\">⚡ Load WKND Site Preset</button>\n"
                + "          <button class=\"btn btn-outline\" onclick=\"clearForm()\">✨ Clear Form</button>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Pages -->\n"
                + "    <div id=\"tab-pages\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Discovered Pages & Opt-In Eligibility</div>\n"
                + "        <table id=\"table-pages\"><thead><tr><th>AEM Content Path</th><th>Page Title</th><th>Template</th><th>Eligibility Status</th></tr></thead><tbody><tr><td colspan=\"4\">Run a Dry Run to discover pages.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Components -->\n"
                + "    <div id=\"tab-components\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Component Intelligence & Block Mapping</div>\n"
                + "        <table id=\"table-components\"><thead><tr><th>AEM Resource Type</th><th>Title</th><th>Group</th><th>Proposed EDS Block</th><th>Capability Classification</th></tr></thead><tbody><tr><td colspan=\"5\">Run a Dry Run to classify components.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Estimate -->\n"
                + "    <div id=\"tab-estimate\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Step-by-Step Derivation Trail & Cost Modeling</div>\n"
                + "        <pre id=\"estimate-trail\" style=\"font-family:var(--font-mono); font-size:0.85rem; color:#38bdf8; line-height:1.7; background:#060911; padding:18px; border-radius:6px; border:1px solid var(--surface-border);\">Run a Dry Run to compute formal mathematical derivation trail.</pre>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Redirects -->\n"
                + "    <div id=\"tab-redirects\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">301 URL Redirect Map Generator</div>\n"
                + "        <table id=\"table-redirects\"><thead><tr><th>Source URL</th><th>Target URL</th><th>Status Code</th><th>Conflict Analysis</th></tr></thead><tbody><tr><td colspan=\"4\">No redirects mapped.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Dependencies -->\n"
                + "    <div id=\"tab-dependencies\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">JCR Dependency Tree & Blast Radius</div>\n"
                + "        <table id=\"table-dependencies\"><thead><tr><th>Source Node</th><th>Target Node</th><th>Edge Relationship</th><th>Impact Severity</th></tr></thead><tbody><tr><td colspan=\"4\">No dependencies computed.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Rollout -->\n"
                + "    <div id=\"tab-rollout\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Staged Progressive Canary Rollout</div>\n"
                + "        <table id=\"table-rollout\"><thead><tr><th>Stage #</th><th>Stage Name</th><th>Target Traffic %</th><th>Status</th></tr></thead><tbody><tr><td colspan=\"4\">No rollout stages initialized.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Repairs -->\n"
                + "    <div id=\"tab-repairs\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Self-Repair Diagnostics & Auto-Fix Log</div>\n"
                + "        <table id=\"table-repairs\"><thead><tr><th>Target File / Block</th><th>Attempt #</th><th>Issue Category</th><th>Fix Status</th></tr></thead><tbody><tr><td colspan=\"4\">No repair attempts recorded.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Benchmarks -->\n"
                + "    <div id=\"tab-benchmarks\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Agent Benchmark Performance Samples</div>\n"
                + "        <table id=\"table-benchmarks\"><thead><tr><th>Agent</th><th>Operation</th><th>Duration</th><th>Cost (µ$)</th></tr></thead><tbody><tr><td colspan=\"4\">No benchmark samples recorded.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Events -->\n"
                + "    <div id=\"tab-events\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Live Event Stream & Audit Log</div>\n"
                + "        <div id=\"events-log\" class=\"log-terminal\" style=\"height:450px;\"></div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "\n"
                + "  <div id=\"toast\" class=\"toast\"></div>\n"
                + "\n"
                + "  <script>\n"
                + "    let currentProjectId = 'wknd-site';\n"
                + "    let projectsList = [];\n"
                + "\n"
                + "    const api = (path, opts) => {\n"
                + "      const base = (document.querySelector('base')||{}).href || '/bin/aem-eds-modernizer/api/';\n"
                + "      return fetch(base + path, opts).then(r => r.json());\n"
                + "    };\n"
                + "\n"
                + "    function showToast(msg) {\n"
                + "      const t = document.getElementById('toast');\n"
                + "      t.innerText = msg;\n"
                + "      t.classList.add('show');\n"
                + "      setTimeout(() => t.classList.remove('show'), 3500);\n"
                + "    }\n"
                + "\n"
                + "    function showTab(tabId) {\n"
                + "      document.querySelectorAll('.nav-tab').forEach(t => t.classList.remove('active'));\n"
                + "      document.querySelectorAll('.tab-content').forEach(c => c.style.display = 'none');\n"
                + "      const btn = Array.from(document.querySelectorAll('.nav-tab')).find(b => b.getAttribute('onclick') && b.getAttribute('onclick').includes(tabId));\n"
                + "      if (btn) btn.classList.add('active');\n"
                + "      const target = document.getElementById('tab-' + tabId);\n"
                + "      if (target) target.style.display = 'block';\n"
                + "    }\n"
                + "\n"
                + "    function setPipelineStep(stepId, state) {\n"
                + "      const el = document.getElementById('step-' + stepId);\n"
                + "      if (el) {\n"
                + "        if (state === 'done') { el.className = 'step-item done'; }\n"
                + "        else if (state === 'active') { el.className = 'step-item active'; }\n"
                + "        else { el.className = 'step-item'; }\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    function log(agent, msg) {\n"
                + "      const term = document.getElementById('terminal');\n"
                + "      const eventsLog = document.getElementById('events-log');\n"
                + "      const time = new Date().toLocaleTimeString();\n"
                + "      const line = `<div class=\"log-line\"><span class=\"log-time\">[${time}]</span><span class=\"log-agent\">[${agent}]</span><span>${msg}</span></div>`;\n"
                + "      if (term) { term.innerHTML += line; term.scrollTop = term.scrollHeight; }\n"
                + "      if (eventsLog) { eventsLog.innerHTML += line; eventsLog.scrollTop = eventsLog.scrollHeight; }\n"
                + "    }\n"
                + "\n"
                + "    function onProviderChange() {\n"
                + "      const provider = document.getElementById('cfg-aiProvider').value;\n"
                + "      const modelInput = document.getElementById('cfg-aiModel');\n"
                + "      if (provider === 'anthropic') modelInput.value = 'claude-3-5-sonnet-20241022';\n"
                + "      else if (provider === 'openai') modelInput.value = 'gpt-4o';\n"
                + "      else if (provider === 'gemini') modelInput.value = 'gemini-1.5-pro';\n"
                + "      else if (provider === 'ollama') modelInput.value = 'llama3:8b';\n"
                + "    }\n"
                + "\n"
                + "    function loadWkndPreset() {\n"
                + "      document.getElementById('cfg-id').value = 'wknd-site';\n"
                + "      document.getElementById('cfg-name').value = 'WKND Site Modernization';\n"
                + "      document.getElementById('cfg-authorUrl').value = 'http://localhost:4502';\n"
                + "      document.getElementById('cfg-publishUrl').value = 'http://localhost:4503';\n"
                + "      document.getElementById('cfg-contentRoot').value = '/content/wknd';\n"
                + "      document.getElementById('cfg-pageScope').value = '/content/wknd/*';\n"
                + "      document.getElementById('cfg-repoUrl').value = 'https://github.com/my-org/wknd-eds';\n"
                + "      document.getElementById('cfg-branch').value = 'main';\n"
                + "      document.getElementById('cfg-markerProp').value = 'edsModernize';\n"
                + "      document.getElementById('cfg-markerVal').value = 'true';\n"
                + "      document.getElementById('cfg-authoringStrategy').value = 'UNIVERSAL_EDITOR';\n"
                + "      document.getElementById('cfg-aiProvider').value = 'anthropic';\n"
                + "      document.getElementById('cfg-aiModel').value = 'claude-3-5-sonnet-20241022';\n"
                + "      document.getElementById('cfg-maxBudget').value = '100.00';\n"
                + "      document.getElementById('cfg-maxRepair').value = '5';\n"
                + "      showToast('Loaded WKND Site Configuration Preset');\n"
                + "    }\n"
                + "\n"
                + "    function clearForm() {\n"
                + "      document.getElementById('cfg-id').value = 'project-' + Math.random().toString(36).substring(2,7);\n"
                + "      document.getElementById('cfg-name').value = '';\n"
                + "      document.getElementById('cfg-authorUrl').value = 'http://localhost:4502';\n"
                + "      document.getElementById('cfg-publishUrl').value = '';\n"
                + "      document.getElementById('cfg-contentRoot').value = '/content/';\n"
                + "      document.getElementById('cfg-pageScope').value = '';\n"
                + "      document.getElementById('cfg-repoUrl').value = '';\n"
                + "      document.getElementById('cfg-figmaUrl').value = '';\n"
                + "    }\n"
                + "\n"
                + "    async function saveProjectConfig() {\n"
                + "      const payload = {\n"
                + "        id: document.getElementById('cfg-id').value.trim() || 'project-1',\n"
                + "        name: document.getElementById('cfg-name').value.trim() || 'Untitled Project',\n"
                + "        aemAuthorUrl: document.getElementById('cfg-authorUrl').value.trim(),\n"
                + "        aemPublishUrl: document.getElementById('cfg-publishUrl').value.trim(),\n"
                + "        contentRoot: document.getElementById('cfg-contentRoot').value.trim(),\n"
                + "        pageScope: document.getElementById('cfg-pageScope').value.trim(),\n"
                + "        edsGitRepoUrl: document.getElementById('cfg-repoUrl').value.trim(),\n"
                + "        edsBranch: document.getElementById('cfg-branch').value.trim(),\n"
                + "        figmaUrl: document.getElementById('cfg-figmaUrl').value.trim(),\n"
                + "        markerProperty: document.getElementById('cfg-markerProp').value.trim(),\n"
                + "        markerValue: document.getElementById('cfg-markerVal').value.trim(),\n"
                + "        authoringStrategy: document.getElementById('cfg-authoringStrategy').value,\n"
                + "        aiProvider: document.getElementById('cfg-aiProvider').value,\n"
                + "        aiModel: document.getElementById('cfg-aiModel').value.trim(),\n"
                + "        maxBudgetUsd: parseFloat(document.getElementById('cfg-maxBudget').value) || 100.0,\n"
                + "        maxRepairAttempts: parseInt(document.getElementById('cfg-maxRepair').value, 10) || 5\n"
                + "      };\n"
                + "\n"
                + "      log('connection', `Saving project '${payload.name}' (${payload.id}) & verifying AEM endpoint...`);\n"
                + "      try {\n"
                + "        const saved = await api('projects', {\n"
                + "          method: 'POST',\n"
                + "          headers: { 'Content-Type': 'application/json' },\n"
                + "          body: JSON.stringify(payload)\n"
                + "        });\n"
                + "        currentProjectId = saved.id;\n"
                + "        log('connection', `Project saved successfully: ContentRoot=${payload.contentRoot}, EDS Repo=${payload.edsGitRepoUrl}`);\n"
                + "        showToast(`Project '${saved.name}' Saved & Connected!`);\n"
                + "        document.getElementById('btn-dryrun').disabled = false;\n"
                + "        setPipelineStep('connect', 'done');\n"
                + "        setPipelineStep('dryrun', 'active');\n"
                + "        await loadProjectsList();\n"
                + "        showTab('overview');\n"
                + "      } catch (err) {\n"
                + "        log('error', `Failed to save project: ${err.message}`);\n"
                + "        showToast('Error saving project');\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function loadProjectsList() {\n"
                + "      try {\n"
                + "        projectsList = await api('projects');\n"
                + "        const select = document.getElementById('project-select');\n"
                + "        if (projectsList && projectsList.length > 0) {\n"
                + "          select.innerHTML = projectsList.map(p => `<option value=\"${p.id}\" ${p.id === currentProjectId ? 'selected' : ''}>${p.name || p.id}</option>`).join('')\n"
                + "            + '<option value=\"new\">+ Create New Project...</option>';\n"
                + "        }\n"
                + "      } catch (e) { console.log(e); }\n"
                + "    }\n"
                + "\n"
                + "    async function onProjectSelectChange() {\n"
                + "      const val = document.getElementById('project-select').value;\n"
                + "      if (val === 'new') {\n"
                + "        clearForm();\n"
                + "        showTab('setup');\n"
                + "      } else {\n"
                + "        currentProjectId = val;\n"
                + "        await populateFormFromProject(val);\n"
                + "        await refreshDashboard();\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function populateFormFromProject(id) {\n"
                + "      const p = projectsList.find(x => x.id === id) || await api(`projects/${id}`);\n"
                + "      if (p) {\n"
                + "        document.getElementById('cfg-id').value = p.id || '';\n"
                + "        document.getElementById('cfg-name').value = p.name || '';\n"
                + "        document.getElementById('cfg-authorUrl').value = p.aemAuthorUrl || 'http://localhost:4502';\n"
                + "        document.getElementById('cfg-publishUrl').value = p.aemPublishUrl || '';\n"
                + "        document.getElementById('cfg-contentRoot').value = p.contentRoot || '/content/wknd';\n"
                + "        document.getElementById('cfg-pageScope').value = p.pageScope || '';\n"
                + "        document.getElementById('cfg-repoUrl').value = p.edsGitRepoUrl || '';\n"
                + "        document.getElementById('cfg-branch').value = p.edsBranch || 'main';\n"
                + "        document.getElementById('cfg-figmaUrl').value = p.figmaUrl || '';\n"
                + "        document.getElementById('cfg-markerProp').value = p.markerProperty || 'edsModernize';\n"
                + "        document.getElementById('cfg-markerVal').value = p.markerValue || 'true';\n"
                + "        document.getElementById('cfg-authoringStrategy').value = p.authoringStrategy || 'UNIVERSAL_EDITOR';\n"
                + "        document.getElementById('cfg-aiProvider').value = p.aiProvider || 'anthropic';\n"
                + "        document.getElementById('cfg-aiModel').value = p.aiModel || 'claude-3-5-sonnet-20241022';\n"
                + "        document.getElementById('cfg-maxBudget').value = p.maxBudgetUsd || 100.0;\n"
                + "        document.getElementById('cfg-maxRepair').value = p.maxRepairAttempts || 5;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function runDryRun() {\n"
                + "      document.getElementById('btn-dryrun').disabled = true;\n"
                + "      setPipelineStep('dryrun', 'active');\n"
                + "      log('orchestrator', `Starting Mandatory Dry Run for project '${currentProjectId}'...`);\n"
                + "      try {\n"
                + "        const job = await api(`projects/${currentProjectId}/dryrun`, { method: 'POST' });\n"
                + "        log('orchestrator', `Dry Run execution completed with state: ${job.state}`);\n"
                + "        setPipelineStep('dryrun', 'done');\n"
                + "        setPipelineStep('analyze', 'done');\n"
                + "        setPipelineStep('contract', 'active');\n"
                + "        await refreshDashboard();\n"
                + "        document.getElementById('btn-migrate').disabled = false;\n"
                + "        showToast('Dry Run Completed! Review components, estimate & contract.');\n"
                + "      } catch (err) {\n"
                + "        log('error', `Dry run failed: ${err.message}`);\n"
                + "      } finally {\n"
                + "        document.getElementById('btn-dryrun').disabled = false;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function runMigration() {\n"
                + "      document.getElementById('btn-migrate').disabled = true;\n"
                + "      setPipelineStep('contract', 'done');\n"
                + "      setPipelineStep('migrate', 'active');\n"
                + "      log('orchestrator', `Executing Approved Migration pipeline for project '${currentProjectId}'...`);\n"
                + "      try {\n"
                + "        const job = await api(`projects/${currentProjectId}/migrate`, { method: 'POST' });\n"
                + "        log('orchestrator', `Migration finished with state: ${job.state}`);\n"
                + "        setPipelineStep('migrate', 'done');\n"
                + "        setPipelineStep('verify', 'done');\n"
                + "        await refreshDashboard();\n"
                + "        showToast('Migration Pipeline Completed Successfully!');\n"
                + "      } catch (err) {\n"
                + "        log('error', `Migration failed: ${err.message}`);\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function refreshDashboard() {\n"
                + "      try {\n"
                + "        const inv = await api(`projects/${currentProjectId}/inventory`);\n"
                + "        if (inv && inv.pages) {\n"
                + "          document.getElementById('stat-pages').innerText = inv.pages.length;\n"
                + "          document.getElementById('stat-eligible').innerText = (inv.eligiblePages || inv.pages.length) + ' eligible';\n"
                + "          document.getElementById('stat-components').innerText = inv.components ? inv.components.length : 0;\n"
                + "          renderPagesTable(inv.pages);\n"
                + "          renderComponentsTable(inv.components);\n"
                + "        }\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const plan = await api(`projects/${currentProjectId}/plan`);\n"
                + "        if (plan) {\n"
                + "          document.getElementById('stat-cost').innerText = '$' + (plan.costExpected || 0).toFixed(2);\n"
                + "          document.getElementById('stat-requests').innerText = (plan.aiRequestsExpected || 0) + ' AI calls estimated';\n"
                + "          document.getElementById('stat-time').innerText = (plan.timeExpectedSec || 0) + 's';\n"
                + "          document.getElementById('stat-range').innerText = `Lo: ${(plan.timeOptimisticSec||0)}s | Hi: ${(plan.timePessimisticSec||0)}s`;\n"
                + "          if (plan.derivationTrail) {\n"
                + "            document.getElementById('estimate-trail').innerText = plan.derivationTrail.join('\\n');\n"
                + "          }\n"
                + "        }\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const redirects = await api(`projects/${currentProjectId}/redirects`);\n"
                + "        renderRedirectsTable(redirects);\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const deps = await api(`projects/${currentProjectId}/dependencies`);\n"
                + "        renderDependenciesTable(deps);\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const rollout = await api(`projects/${currentProjectId}/rollout-stages`);\n"
                + "        renderRolloutTable(rollout);\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const repairs = await api(`projects/${currentProjectId}/repairs`);\n"
                + "        renderRepairsTable(repairs);\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const benchmarks = await api(`projects/${currentProjectId}/benchmarks`);\n"
                + "        renderBenchmarksTable(benchmarks);\n"
                + "      } catch (e) {}\n"
                + "    }\n"
                + "\n"
                + "    function renderPagesTable(pages) {\n"
                + "      const tbody = document.querySelector('#table-pages tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (pages && pages.length > 0)\n"
                + "        ? pages.map(p => `<tr><td><code>${p.path}</code></td><td>${p.title || '-'}</td><td>${p.template || '-'}</td><td><span style=\"color:${p.eligible !== false ? 'var(--accent)' : 'var(--danger)'}; font-weight:700;\">${p.eligible !== false ? '● ELIGIBLE' : '○ EXCLUDED'}</span></td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No pages discovered yet.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderComponentsTable(components) {\n"
                + "      const tbody = document.querySelector('#table-components tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (components && components.length > 0)\n"
                + "        ? components.map(c => `<tr><td><code>${c.resourceType}</code></td><td>${c.title || '-'}</td><td>${c.group || '-'}</td><td><b style=\"color:var(--primary);\">${c.proposedEdsBlock || '-'}</b></td><td><span style=\"background:rgba(56,189,248,0.1); color:var(--primary); padding:3px 8px; border-radius:4px; font-size:0.75rem; font-weight:700;\">${c.capabilityClassification || 'SUPPORTED'}</span></td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"5\">No components analyzed yet.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderRedirectsTable(list) {\n"
                + "      const tbody = document.querySelector('#table-redirects tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(r => `<tr><td><code>${r.sourceUrl}</code></td><td><code>${r.targetUrl}</code></td><td><span style=\"color:var(--accent); font-weight:700;\">${r.statusCode || 301}</span></td><td>${r.conflict ? '<span style=\"color:var(--warn);\">⚠️ Conflict</span>' : '<span style=\"color:var(--accent);\">OK</span>'}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No redirects mapped.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderDependenciesTable(list) {\n"
                + "      const tbody = document.querySelector('#table-dependencies tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(d => `<tr><td><code>${d.source}</code></td><td><code>${d.target}</code></td><td><span style=\"color:var(--primary);\">${d.edgeType}</span></td><td>${d.impactLevel || 'LOW'}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No dependencies computed.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderRolloutTable(list) {\n"
                + "      const tbody = document.querySelector('#table-rollout tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(s => `<tr><td>#${s.stageIndex}</td><td><b>${s.stageName}</b></td><td><span style=\"color:var(--accent); font-weight:700;\">${s.targetTrafficPercent}%</span></td><td>${s.status}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No rollout stages initialized.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderRepairsTable(list) {\n"
                + "      const tbody = document.querySelector('#table-repairs tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(r => `<tr><td><code>${r.targetPath}</code></td><td>#${r.attemptNumber}</td><td>${r.issueCategory || 'STYLE'}</td><td>${r.successful ? '<span style=\"color:var(--accent);\">✅ Fixed</span>' : '<span style=\"color:var(--danger);\">❌ Failed</span>'}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No repair attempts recorded.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderBenchmarksTable(list) {\n"
                + "      const tbody = document.querySelector('#table-benchmarks tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(b => `<tr><td><b>${b.agent}</b></td><td>${b.operation}</td><td>${b.durationMs}ms</td><td>${(b.costMicros || 0).toFixed(1)}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No benchmark samples recorded.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    window.addEventListener('load', async () => {\n"
                + "      try {\n"
                + "        await loadProjectsList();\n"
                + "        if (projectsList && projectsList.length > 0) {\n"
                + "          currentProjectId = projectsList[0].id;\n"
                + "          await populateFormFromProject(currentProjectId);\n"
                + "          await refreshDashboard();\n"
                + "        }\n"
                + "      } catch (e) {\n"
                + "        console.log('Dashboard init:', e);\n"
                + "      }\n"
                + "    });\n"
                + "  </script>\n"
                + "</body>\n"
                + "</html>\n";
    }
}
