package com.adobe.aem.modernizer.dashboard;

/**
 * Legacy inlined Modernizer Dashboard SPA (Master §3, §31, ADR 0002).
 * <p>
 * <strong>Deprecated for runtime serving.</strong> The live UI is the HTL page component
 * {@code aem-eds-modernizer/components/page/home} ({@code home.html} + clientlibs).
 * Kept for unit tests and offline/standalone HTML generation only.
 */
@Deprecated
public final class StaticDashboard {

    private StaticDashboard() {}

    public static String html() {
        return html("/bin/aem-eds-modernizer/api");
    }

    public static String html(String apiBase) {
        String base = (apiBase == null || apiBase.trim().isEmpty())
                ? "/bin/aem-eds-modernizer/api" : apiBase.trim();
        if (!base.endsWith("/")) {
            base += "/";
        }

        return htmlHead(base) + htmlMain() + PreviewPanel.script() + htmlScript();
    }

    private static String htmlHead(String base) {
        return "<!doctype html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <title>AEM → EDS Modernizer</title>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
                + "  <base href=\"" + base + "\">\n"
                + "  <style>\n"
                + "    :root {\n"
                + "      --bg-dark: #090d16;\n"
                + "      --bg-header: rgba(15, 23, 42, 0.9);\n"
                + "      --surface: #131d31;\n"
                + "      --surface-card: #1e293b;\n"
                + "      --surface-border: #334155;\n"
                + "      --surface-focus: #475569;\n"
                + "      --primary: #38bdf8;\n"
                + "      --primary-hover: #0ea5e9;\n"
                + "      --accent: #10b981;\n"
                + "      --accent-hover: #059669;\n"
                + "      --warn: #f59e0b;\n"
                + "      --danger: #ef4444;\n"
                + "      --purple: #a855f7;\n"
                + "      --text: #f8fafc;\n"
                + "      --text-muted: #94a3b8;\n"
                + "      --text-dim: #64748b;\n"
                + "      --font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;\n"
                + "      --font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;\n"
                + "    }\n"
                + "    * { box-sizing: border-box; margin: 0; padding: 0; }\n"
                + "    body { background: var(--bg-dark); color: var(--text); font-family: var(--font-sans); min-height: 100vh; display: flex; flex-direction: column; }\n"
                + "    header { background: var(--bg-header); backdrop-filter: blur(12px); border-bottom: 1px solid var(--surface-border); padding: 14px 28px; display: flex; justify-content: space-between; align-items: center; position: sticky; top: 0; z-index: 100; gap: 16px; flex-wrap: wrap; }\n"
                + "    .brand { display: flex; align-items: center; gap: 12px; font-size: 1.25rem; font-weight: 700; color: var(--text); text-decoration: none; }\n"
                + "    .brand svg { fill: var(--primary); }\n"
                + "    .header-center { display: flex; align-items: center; gap: 12px; }\n"
                + "    .project-selector { background: var(--surface-card); border: 1px solid var(--surface-border); color: var(--text); padding: 7px 14px; border-radius: 6px; font-size: 0.85rem; font-weight: 600; cursor: pointer; outline: none; }\n"
                + "    .header-right { display: flex; align-items: center; gap: 10px; }\n"
                + "    .status-badge { display: inline-flex; align-items: center; gap: 6px; padding: 5px 12px; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; background: rgba(16,185,129,0.15); color: var(--accent); border: 1px solid rgba(16,185,129,0.3); }\n"
                + "    .container { max-width: 1440px; margin: 0 auto; padding: 24px 28px; width: 100%; flex: 1; }\n"
                + "    .nav-tabs { display: flex; gap: 6px; border-bottom: 1px solid var(--surface-border); margin-bottom: 24px; overflow-x: auto; }\n"
                + "    .nav-tab { padding: 10px 18px; border: none; background: transparent; color: var(--text-muted); font-size: 0.88rem; font-weight: 600; cursor: pointer; border-bottom: 2px solid transparent; transition: all 0.2s; white-space: nowrap; border-radius: 6px 6px 0 0; }\n"
                + "    .nav-tab:hover { color: var(--text); background: rgba(255,255,255,0.03); }\n"
                + "    .nav-tab.active { color: var(--primary); border-bottom-color: var(--primary); background: rgba(56,189,248,0.08); }\n"
                + "    .actions { display: flex; gap: 10px; margin-bottom: 24px; flex-wrap: wrap; align-items: center; justify-content: space-between; }\n"
                + "    .actions-left, .actions-right { display: flex; gap: 10px; flex-wrap: wrap; align-items: center; }\n"
                + "    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 16px; margin-bottom: 24px; }\n"
                + "    .split-layout { display: grid; grid-template-columns: minmax(240px, 320px) 1fr; gap: 16px; }\n"
                + "    .metric-list, .data-list, .estimate-list { list-style: none; display: flex; flex-direction: column; gap: 8px; }\n"
                + "    .metric-row, .data-list-item { display: grid; grid-template-columns: 1fr auto; gap: 4px 12px; padding: 12px 14px; background: var(--surface-card); border: 1px solid var(--surface-border); border-radius: 8px; }\n"
                + "    .metric-label { font-size: 0.75rem; font-weight: 700; text-transform: uppercase; color: var(--text-muted); }\n"
                + "    .metric-value { font-size: 1.35rem; font-weight: 800; }\n"
                + "    .metric-hint, .data-list-meta { font-size: 0.75rem; color: var(--text-dim); }\n"
                + "    .data-list-title { font-weight: 700; }\n"
                + "    .data-list-block { color: var(--primary); font-weight: 700; }\n"
                + "    .data-list-empty { padding: 16px; color: var(--text-dim); text-align: center; }\n"
                + "    .nav-group-label { font-size: 0.68rem; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; color: var(--text-dim); padding: 4px 8px; }\n"
                + "    .card { background: var(--surface); border: 1px solid var(--surface-border); border-radius: 10px; padding: 22px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.2); position: relative; }\n"
                + "    .card-title { font-size: 0.82rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted); margin-bottom: 10px; display: flex; justify-content: space-between; align-items: center; }\n"
                + "    .card-val { font-size: 1.9rem; font-weight: 800; color: var(--text); }\n"
                + "    .card-sub { font-size: 0.8rem; color: var(--text-muted); margin-top: 6px; }\n"
                + "    .btn { display: inline-flex; align-items: center; justify-content: center; gap: 8px; padding: 9px 18px; border-radius: 7px; font-weight: 600; font-size: 0.88rem; cursor: pointer; border: none; transition: all 0.2s; text-decoration: none; }\n"
                + "    .btn-primary { background: var(--primary); color: #090d16; }\n"
                + "    .btn-primary:hover { background: var(--primary-hover); transform: translateY(-1px); }\n"
                + "    .btn-accent { background: var(--accent); color: #090d16; }\n"
                + "    .btn-accent:hover { background: var(--accent-hover); transform: translateY(-1px); }\n"
                + "    .btn-danger { background: rgba(239,68,68,0.18); color: #fecaca; border: 1px solid rgba(239,68,68,0.45); }\n"
                + "    .btn-danger:hover { background: rgba(239,68,68,0.32); }\n"
                + "    .btn:disabled { opacity: 0.45; cursor: not-allowed; }\n"
                + "    .btn-outline { background: transparent; border: 1px solid var(--surface-border); color: var(--text); }\n"
                + "    .btn-outline:hover { background: var(--surface-card); border-color: var(--surface-focus); }\n"
                + "    .btn-warn { background: var(--warn); color: #090d16; }\n"
                + "    .btn:disabled { opacity: 0.45; cursor: not-allowed; transform: none !important; }\n"
                + "    .form-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 20px; }\n"
                + "    .form-section { background: var(--surface-card); border: 1px solid var(--surface-border); border-radius: 8px; padding: 20px; }\n"
                + "    .form-section-title { font-size: 0.95rem; font-weight: 700; color: var(--primary); margin-bottom: 16px; border-bottom: 1px solid rgba(255,255,255,0.06); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; }\n"
                + "    .form-group { margin-bottom: 14px; }\n"
                + "    .form-label { display: block; font-size: 0.8rem; font-weight: 600; color: var(--text-muted); margin-bottom: 6px; }\n"
                + "    .form-control { width: 100%; background: #0b1120; border: 1px solid var(--surface-border); border-radius: 6px; padding: 9px 12px; color: var(--text); font-size: 0.88rem; font-family: var(--font-sans); transition: border-color 0.2s; outline: none; }\n"
                + "    .form-control:focus { border-color: var(--primary); box-shadow: 0 0 0 2px rgba(56,189,248,0.2); }\n"
                + "    .form-hint { font-size: 0.75rem; color: var(--text-dim); margin-top: 4px; }\n"
                + "    .pipeline-stepper { display: flex; gap: 4px; margin-bottom: 24px; background: var(--surface-card); border: 1px solid var(--surface-border); border-radius: 8px; padding: 8px; overflow-x: auto; }\n"
                + "    .step-item { flex: 1; min-width: 130px; text-align: center; padding: 8px 12px; border-radius: 6px; font-size: 0.78rem; font-weight: 700; color: var(--text-muted); background: transparent; transition: all 0.2s; }\n"
                + "    .step-item.active { background: rgba(56,189,248,0.15); color: var(--primary); border: 1px solid rgba(56,189,248,0.3); }\n"
                + "    .step-item.done { background: rgba(16,185,129,0.12); color: var(--accent); }\n"
                + "    table { width: 100%; border-collapse: collapse; text-align: left; font-size: 0.875rem; }\n"
                + "    th, td { padding: 12px 16px; border-bottom: 1px solid var(--surface-border); }\n"
                + "    th { color: var(--text-muted); font-weight: 600; background: rgba(15,23,42,0.6); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.04em; }\n"
                + "    tr:hover td { background: rgba(255,255,255,0.02); }\n"
                + "    .log-terminal { background: #060911; border: 1px solid var(--surface-border); border-radius: 8px; padding: 16px; font-family: var(--font-mono); font-size: 0.82rem; height: 360px; overflow-y: auto; color: #a5b4fc; box-shadow: inset 0 2px 4px rgba(0,0,0,0.4); }\n"
                + "    .ws-layout { display:flex; height:100%; min-height:720px; }\n"
                + "    .ws-sidebar { width:280px; border-right:1px solid var(--surface-border); overflow:auto; background:#0f172a; }\n"
                + "    .ws-tree-title { padding:10px 12px; font-size:0.72rem; font-weight:700; letter-spacing:0.06em; text-transform:uppercase; color:var(--text-dim); }\n"
                + "    #ws-file-tree { list-style:none; padding:0 8px 12px; }\n"
                + "    .ws-tree-empty { padding:12px; color:var(--text-dim); font-size:0.8rem; }\n"
                + "    .ws-file-row { display:flex; align-items:flex-start; gap:4px; margin-bottom:2px; }\n"
                + "    .ws-file-btn { flex:1; text-align:left; background:transparent; border:none; color:#cbd5e1; font-family:var(--font-mono); font-size:0.75rem; padding:7px 8px; border-radius:4px; cursor:pointer; word-break:break-all; }\n"
                + "    .ws-file-btn:hover, .ws-file-btn.active { background:rgba(56,189,248,0.12); color:var(--primary); }\n"
                + "    .ws-file-del { flex:none; background:transparent; border:1px solid rgba(239,68,68,0.35); color:#fca5a5; font-size:0.68rem; font-weight:700; padding:5px 7px; border-radius:4px; cursor:pointer; }\n"
                + "    .ws-file-del:hover { background:rgba(239,68,68,0.18); color:#fecaca; }\n"
                + "    .ws-main { flex:1; display:flex; flex-direction:column; min-width:0; }\n"
                + "    .ws-toolbar { display:flex; justify-content:space-between; align-items:center; gap:8px; padding:8px 12px; border-bottom:1px solid var(--surface-border); font-size:0.8rem; color:#e2e8f0; }\n"
                + "    .ws-editor-pane { flex:1; display:flex; min-height:0; background:#1e1e1e; }\n"
                + "    .ws-line-numbers { margin:0; padding:14px 10px 14px 12px; min-width:3.2em; text-align:right; border-right:1px solid #333; background:#252526; color:#858585; font-family:var(--font-mono); font-size:0.82rem; line-height:1.5; overflow:hidden; user-select:none; white-space:pre; }\n"
                + "    .ws-editor { flex:1; width:100%; height:100%; border:none; resize:none; background:#1e1e1e; color:#d4d4d4; font-family:var(--font-mono); font-size:0.82rem; line-height:1.5; padding:14px; outline:none; overflow:auto; white-space:pre; }\n"
                + "    .log-line { margin-bottom: 5px; line-height: 1.5; word-break: break-all; }\n"
                + "    .log-time { color: var(--text-dim); margin-right: 8px; }\n"
                + "    .log-agent { color: var(--primary); font-weight: 700; margin-right: 8px; }\n"
                + "    .toast { position: fixed; bottom: 24px; right: 24px; background: var(--surface-card); border: 1px solid var(--surface-border); color: var(--text); padding: 14px 20px; border-radius: 8px; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.5); z-index: 1000; font-size: 0.9rem; display: none; }\n"
                + "    .toast.show { display: block; animation: slideIn 0.3s ease; }\n"
                + "    @keyframes slideIn { from { transform: translateY(20px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }\n"
                + "    " + PreviewPanel.css() + "\n"
                + "  </style>\n"
                + "</head>\n";
    }

    private static String htmlMain() {
        return ""
                + "<body>\n"
                + "  <header>\n"
                + "    <a class=\"brand\" href=\"#\">\n"
                + "      <svg width=\"26\" height=\"26\" viewBox=\"0 0 24 24\"><path d=\"M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5\"/></svg>\n"
                + "      <span>AEM → EDS Modernizer</span>\n"
                + "    </a>\n"
                + "    <div class=\"header-center\">\n"
                + "      <label style=\"font-size:0.8rem; color:var(--text-muted); font-weight:600;\">Active Project:</label>\n"
                + "      <select id=\"project-select\" class=\"project-selector\" onchange=\"onProjectSelectChange()\">\n"
                + "        <option value=\"wknd-site\">WKND Site Modernization</option>\n"
                + "        <option value=\"new\">+ Create New Project...</option>\n"
                + "      </select>\n"
                + "    </div>\n"
                + "    <div class=\"header-right\">\n"
                + "      <div id=\"system-status\" class=\"status-badge\">● Ready</div>\n"
                + "    </div>\n"
                + "  </header>\n"
                + "\n"
                + "  <div class=\"container\">\n"
                + "    <div class=\"actions\">\n"
                + "      <div class=\"actions-left\">\n"
                + "        <button class=\"btn btn-outline\" onclick=\"showTab('setup')\">⚙️ Project Configuration</button>\n"
                + "        <button id=\"btn-dryrun\" class=\"btn btn-primary\" onclick=\"runDryRun()\">🔍 Run Dry Run</button>\n"
                + "        <button id=\"btn-migrate\" class=\"btn btn-accent\" onclick=\"runMigration()\" disabled>⚡ Generate & Build Blocks</button>\n"
                + "        <button id=\"btn-publish\" class=\"btn btn-accent\" onclick=\"runPushToGit()\" disabled>🚀 Create PR</button>\n"
                + "      </div>\n"
                + "      <div class=\"actions-right\">\n"
                + "        <button id=\"btn-delete\" class=\"btn btn-danger\" type=\"button\" onclick=\"deleteCurrentProject()\">🗑️ Delete Project</button>\n"
                + "        <button class=\"btn btn-outline\" onclick=\"refreshDashboard()\">🔄 Refresh</button>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Pipeline Stepper -->\n"
                + "    <div class=\"pipeline-stepper\">\n"
                + "      <div id=\"step-connect\" class=\"step-item active\">1. CONNECT</div>\n"
                + "      <div id=\"step-dryrun\" class=\"step-item\">2. DRY RUN</div>\n"
                + "      <div id=\"step-build\" class=\"step-item\">3. GENERATE BLOCKS</div>\n"
                + "      <div id=\"step-validate\" class=\"step-item\">4. REVIEW &amp; VALIDATE</div>\n"
                + "      <div id=\"step-vscode\" class=\"step-item\">5. REVIEW IN VS CODE</div>\n"
                + "      <div id=\"step-publish\" class=\"step-item\">6. OPEN PULL REQUEST</div>\n"
                + "    </div>\n"
                + "\n"
                + "    <nav class=\"nav-tabs\">\n"
                + "      <div class=\"nav-group\"><div class=\"nav-group-label\">Results</div>\n"
                + "      <button class=\"nav-tab active\" onclick=\"showTab('overview')\">Overview</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('components')\">Components</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('estimate')\">Estimates</button></div>\n"
                + "      <div class=\"nav-group\"><div class=\"nav-group-label\">Content</div>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('pages')\">Pages & Scope</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('github')\">VS Code & GitHub</button></div>\n"
                + "      <div class=\"nav-group\"><div class=\"nav-group-label\">Ops</div>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('redirects')\">301 Redirects</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('dependencies')\">Dependencies Graph</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('rollout')\">Rollout Stages</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('repairs')\">Self-Repair Log</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('benchmarks')\">Benchmarks</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('chat')\">Agent Chat</button></div>\n"
                + "      <div class=\"nav-group\"><div class=\"nav-group-label\">Config</div>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('setup')\">Project Setup</button></div>\n"
                + "    </nav>\n"
                + "\n"
                + "    <!-- Tab: Overview -->\n"
                + "    <div id=\"tab-overview\" class=\"tab-content\">\n"
                + "      <div class=\"split-layout\">\n"
                + "        <div class=\"card\"><div class=\"card-title\">Migration snapshot</div>\n"
                + "        <ul class=\"metric-list\">\n"
                + "          <li class=\"metric-row\"><span class=\"metric-label\">Pages discovered</span><span class=\"metric-value\" id=\"stat-pages\">0</span><span class=\"metric-hint\" id=\"stat-eligible\">0 in migration scope</span></li>\n"
                + "          <li class=\"metric-row\"><span class=\"metric-label\">Components mapped</span><span class=\"metric-value\" id=\"stat-components\">0</span><span class=\"metric-hint\">Mapped to Edge Delivery blocks</span></li>\n"
                + "          <li class=\"metric-row\"><span class=\"metric-label\">Expected AI cost</span><span class=\"metric-value\" id=\"stat-cost\">$0.00</span><span class=\"metric-hint\" id=\"stat-requests\">0 AI calls estimated</span></li>\n"
                + "          <li class=\"metric-row\"><span class=\"metric-label\">Estimated duration</span><span class=\"metric-value\" id=\"stat-time\">0s</span><span class=\"metric-hint\" id=\"stat-range\">Lo: 0s | Hi: 0s</span></li>\n"
                + "        </ul></div>\n"
                + "        <div class=\"card\"><div class=\"card-title\">Real-time Activity Stream</div>\n"
                + "        <div id=\"terminal\" class=\"log-terminal\">AEM → EDS Modernizer ready. Configure your project or run a Dry Run.</div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Project Setup & Details Form -->\n"
                + "    <div id=\"tab-setup\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\" style=\"margin-bottom: 20px;\">\n"
                + "        <div class=\"card-title\">Modernizer Project & Connection Configuration</div>\n"
                + "        <p style=\"font-size:0.85rem; color:var(--text-muted); margin-bottom:20px;\">\n"
                + "          Configure your source AEM environment, content scope, Edge Delivery Services Git repository, AI model, and migration safety bounds.\n"
                + "        </p>\n"
                + "        <div class=\"form-grid\">\n"
                + "          <!-- Section 1: AEM Connection -->\n"
                + "          <div class=\"form-section\">\n"
                + "            <div class=\"form-section-title\">🌐 AEM Environment & Scope</div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Project ID</label>\n"
                + "              <input type=\"text\" id=\"cfg-id\" class=\"form-control\" value=\"wknd-site\" placeholder=\"e.g. wknd-site\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Project Name</label>\n"
                + "              <input type=\"text\" id=\"cfg-name\" class=\"form-control\" value=\"WKND Site Modernization\" placeholder=\"e.g. WKND Site Modernization\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">AEM Author URL (Cloud or Local)</label>\n"
                + "              <input type=\"text\" id=\"cfg-authorUrl\" class=\"form-control\" value=\"http://localhost:4502\" placeholder=\"https://author-pXXXXX-eYYYYY.adobeaemcloud.com or http://localhost:4502\">\n"
                + "              <div class=\"form-hint\">Secure OSGi connection via modernizer-service principal</div>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">AEM Publish URL (Optional)</label>\n"
                + "              <input type=\"text\" id=\"cfg-publishUrl\" class=\"form-control\" value=\"http://localhost:4503\" placeholder=\"https://publish-pXXXXX-eYYYYY.adobeaemcloud.com\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Content Root Path</label>\n"
                + "              <input type=\"text\" id=\"cfg-contentRoot\" class=\"form-control\" value=\"/content/wknd\" placeholder=\"/content/wknd\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Page / Subtree Scope (Optional)</label>\n"
                + "              <input type=\"text\" id=\"cfg-pageScope\" class=\"form-control\" value=\"/content/wknd/*\" placeholder=\"/content/wknd/us/en or /content/wknd/*\">\n"
                + "            </div>\n"
                + "          </div>\n"
                + "\n"
                + "          <!-- Section 2: Target EDS & Figma -->\n"
                + "          <div class=\"form-section\">\n"
                + "            <div class=\"form-section-title\">🚀 Target EDS & Design</div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">EDS Git Repository URL</label>\n"
                + "              <input type=\"text\" id=\"cfg-repoUrl\" class=\"form-control\" value=\"https://github.com/my-org/wknd-eds\" placeholder=\"https://github.com/my-org/my-eds-repo\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Target Git Branch</label>\n"
                + "              <input type=\"text\" id=\"cfg-branch\" class=\"form-control\" value=\"main\" placeholder=\"main\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Figma Design File URL (Optional)</label>\n"
                + "              <input type=\"text\" id=\"cfg-figmaUrl\" class=\"form-control\" value=\"\" placeholder=\"https://www.figma.com/file/...\">\n"
                + "              <div class=\"form-hint\">Used for visual token extraction & block styling</div>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Authoring Strategy</label>\n"
                + "              <select id=\"cfg-authoringStrategy\" class=\"form-control\">\n"
                + "                <option value=\"UNIVERSAL_EDITOR\" selected>Universal Editor (AEM Author)</option>\n"
                + "                <option value=\"DOCUMENT_AUTHORING\">Document-based (Google Drive / SharePoint)</option>\n"
                + "                <option value=\"HYBRID\">Hybrid Multi-Authoring</option>\n"
                + "              </select>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Marker Opt-in Property</label>\n"
                + "              <input type=\"text\" id=\"cfg-markerProp\" class=\"form-control\" value=\"edsModernize\" placeholder=\"edsModernize\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Marker Expected Value</label>\n"
                + "              <input type=\"text\" id=\"cfg-markerVal\" class=\"form-control\" value=\"true\" placeholder=\"true or *\">\n"
                + "            </div>\n"
                + "          </div>\n"
                + "\n"
                + "          <!-- Section 3: AI Engine & Safety Bounds -->\n"
                + "          <div class=\"form-section\">\n"
                + "            <div class=\"form-section-title\">🤖 AI Intelligence & Safety Limits</div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">AI Provider Preference</label>\n"
                + "              <select id=\"cfg-aiProvider\" class=\"form-control\" onchange=\"onProviderChange()\">\n"
                + "                <optgroup label=\"Local IDE\">\n"
                + "                <option value=\"antigravity\">Antigravity IDE</option>\n"
                + "                <option value=\"cursor\">Cursor IDE</option>\n"
                + "                <option value=\"claudecode\">Claude Code IDE</option>\n"
                + "                <option value=\"geminicode\">Gemini IDE</option></optgroup>\n"
                + "                <optgroup label=\"Cloud API\">\n"
                + "                <option value=\"anthropic\" selected>Anthropic Claude</option>\n"
                + "                <option value=\"openai\">OpenAI GPT</option>\n"
                + "                <option value=\"gemini\">Google Gemini API</option>\n"
                + "                <option value=\"ollama\">Ollama</option></optgroup>\n"
                + "              </select>\n"
                + "              <div id=\"cloud-api-banner\" style=\"display:none; margin-top:10px; padding:10px 14px; background:#1a2332; border-radius:8px; border:1px solid #334155; color:var(--text-muted); font-size:0.8rem; line-height:1.5;\">\n"
                + "                <strong style=\"color:var(--text);\" id=\"cloud-api-banner-title\">Cloud API</strong>\n"
                + "                — configure the provider API key so calls can authenticate\n"
                + "                (<code style=\"background:#0f172a;padding:2px 5px;border-radius:3px;\" id=\"cloud-api-key-ref\">env:…_API_KEY</code>\n"
                + "                via OSGi <code style=\"background:#0f172a;padding:2px 5px;border-radius:3px;\">AiProviderEndpointConfig</code>).\n"
                + "              </div>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Target AI Model</label>\n"
                + "              <input type=\"text\" id=\"cfg-aiModel\" class=\"form-control\" value=\"claude-3-5-sonnet-20241022\" placeholder=\"model identifier\">\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Max AI Budget Limit (USD)</label>\n"
                + "              <input type=\"number\" id=\"cfg-maxBudget\" class=\"form-control\" value=\"100.00\" step=\"10\">\n"
                + "              <div class=\"form-hint\">Hard ceiling to prevent unexpected API spending</div>\n"
                + "            </div>\n"
                + "            <div class=\"form-group\">\n"
                + "              <label class=\"form-label\">Max Self-Repair Attempts (Bounded Loop)</label>\n"
                + "              <input type=\"number\" id=\"cfg-maxRepair\" class=\"form-control\" value=\"5\" min=\"1\" max=\"10\">\n"
                + "            </div>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "\n"
                + "        <div style=\"margin-top:24px; display:flex; gap:12px; flex-wrap:wrap;\">\n"
                + "          <button class=\"btn btn-primary\" onclick=\"saveProjectConfig()\">💾 Save & Connect Project</button>\n"
                + "          <button class=\"btn btn-outline\" onclick=\"loadWkndPreset()\">⚡ Load WKND Site Preset</button>\n"
                + "          <button class=\"btn btn-outline\" onclick=\"clearForm()\">✨ Clear Form</button>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Pages -->\n"
                + "    <div id=\"tab-pages\" class=\"tab-content\" style=\"display:none;\">\n"
                + PreviewPanel.pagesMarkup()
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Components -->\n"
                + "    <div id=\"tab-components\" class=\"tab-content\" style=\"display:none;\">\n"
                + PreviewPanel.blocksMarkup()
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Estimate -->\n"
                + "    <div id=\"tab-estimate\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Step-by-Step Derivation Trail & Cost Modeling</div>\n"
                + "        <ol id=\"estimate-trail\" class=\"estimate-list\"><li class=\"data-list-empty\">Run a Dry Run to compute the estimate trail.</li></ol>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Redirects -->\n"
                + "    <div id=\"tab-redirects\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">301 URL Redirect Map Generator</div>\n"
                + "        <table id=\"table-redirects\"><thead><tr><th>Source URL</th><th>Target URL</th><th>Status Code</th><th>Conflict Analysis</th></tr></thead><tbody><tr><td colspan=\"4\">No redirects mapped.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Dependencies -->\n"
                + "    <div id=\"tab-dependencies\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">JCR Dependency Tree & Blast Radius</div>\n"
                + "        <table id=\"table-dependencies\"><thead><tr><th>Source Node</th><th>Target Node</th><th>Edge Relationship</th><th>Impact Severity</th></tr></thead><tbody><tr><td colspan=\"4\">No dependencies computed.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Rollout -->\n"
                + "    <div id=\"tab-rollout\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Staged Progressive Canary Rollout</div>\n"
                + "        <table id=\"table-rollout\"><thead><tr><th>Stage #</th><th>Stage Name</th><th>Target Traffic %</th><th>Status</th></tr></thead><tbody><tr><td colspan=\"4\">No rollout stages initialized.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Repairs -->\n"
                + "    <div id=\"tab-repairs\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Self-Repair Diagnostics & Auto-Fix Log</div>\n"
                + "        <table id=\"table-repairs\"><thead><tr><th>Target File / Block</th><th>Attempt #</th><th>Issue Category</th><th>Fix Status</th></tr></thead><tbody><tr><td colspan=\"4\">No repair attempts recorded.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Benchmarks -->\n"
                + "    <div id=\"tab-benchmarks\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Agent Benchmark Performance Samples</div>\n"
                + "        <table id=\"table-benchmarks\"><thead><tr><th>Agent</th><th>Operation</th><th>Duration</th><th>Cost (µ$)</th></tr></thead><tbody><tr><td colspan=\"4\">No benchmark samples recorded.</td></tr></tbody></table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Agent Chat -->\n"
                + "    <div id=\"tab-chat\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Agent Chat</div>\n"
                + "        <div id=\"chat-messages\" class=\"log-terminal\" style=\"height:320px; margin-bottom:12px;\">"
                + "Ask about the project, blocks, or say 'run dry run' / 'show status'.</div>\n"
                + "        <div style=\"display:flex; gap:8px;\">\n"
                + "          <input id=\"chat-input\" class=\"form-control\" placeholder=\"Type a message...\" "
                + "onkeydown=\"if(event.key==='Enter')sendChat()\">\n"
                + "          <button class=\"btn btn-primary\" onclick=\"sendChat()\">Send</button>\n"
                + "        </div>\n"
                + "        <div style=\"margin-top:10px; display:flex; gap:8px; flex-wrap:wrap;\">\n"
                + "          <button class=\"btn btn-outline\" onclick=\"quickChat('show status')\">Status</button>\n"
                + "          <button class=\"btn btn-outline\" onclick=\"quickChat('list blocks')\">Blocks</button>\n"
                + "          <button class=\"btn btn-outline\" onclick=\"quickChat('Show overview stream')\">Overview stream</button>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: VS Code & GitHub Checks -->\n"
                + "    <div id=\"tab-github\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\" style=\"margin-bottom: 20px;\">\n"
                + "        <div class=\"card-title\">💻 Remote Branch & VS Code Editor Workspace</div>\n"
                + "        <p style=\"font-size:0.85rem; color:var(--text-muted); margin-bottom:16px;\">\n"
                + "          Generated files are pushed to the preview branch first (no PR). Review them in vscode.dev, run npm scripts via GitHub Actions, then confirm to open a Pull Request.\n"
                + "        </p>\n"
                + "        <div style=\"display:flex; gap:10px; align-items:center; flex-wrap:wrap;\">\n"
                + "          <div style=\"flex:1; min-width:260px; display:flex; gap:8px; align-items:center;\">\n"
                + "            <label style=\"font-size:0.85rem; font-weight:600; color:var(--text-muted); white-space:nowrap;\">Target Branch:</label>\n"
                + "            <input id=\"github-branch-input\" type=\"text\" class=\"form-control\" placeholder=\"e.g. feat/wknd-site\" style=\"padding:8px 12px;\">\n"
                + "          </div>\n"
                + "          <button id=\"btn-push-blocks-tab\" class=\"btn btn-primary\" onclick=\"pushBlocksAndOpenVsCode()\">🚀 Push Blocks & Open VS Code</button>\n"
                + "          <button class=\"btn btn-outline\" onclick=\"checkBranchStatus()\">🔎 Check CI & Changed Files</button>\n"
                + "          <a id=\"btn-open-vscode-newtab\" href=\"#\" target=\"_blank\" class=\"btn btn-outline\" style=\"display:none;\">🔗 Open in New Tab</a>\n"
                + "          <button class=\"btn btn-outline\" onclick=\"reloadVsCodeFrame()\">🔄 Reload Editor</button>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"card\" style=\"margin-bottom: 20px;\">\n"
                + "        <div class=\"card-title\">npm scripts (GitHub Actions)</div>\n"
                + "        <p style=\"font-size:0.85rem; color:var(--text-muted); margin-bottom:12px;\">vscode.dev has no terminal. These buttons dispatch Actions on the feature branch. lint:fix commits auto-fixed files; build:json commits regenerated component JSON. Heal CI sanitizes block JSON, registers section filters, then runs both.</p>\n"
                + "        <div style=\"display:flex; gap:10px; flex-wrap:wrap; margin-bottom:12px;\">\n"
                + "          <button class=\"btn btn-outline\" id=\"btn-npm-lint\" onclick=\"runNpmScript('lint:fix')\">▶ npm run lint:fix</button>\n"
                + "          <button class=\"btn btn-outline\" id=\"btn-npm-json\" onclick=\"runNpmScript('build:json')\">▶ npm run build:json</button>\n"
                + "          <button class=\"btn btn-outline\" id=\"btn-npm-heal\" onclick=\"runNpmScript('heal')\">Heal CI</button>\n"
                + "        </div>\n"
                + "        <pre id=\"npm-log-terminal\" class=\"log-terminal\" style=\"height:220px; white-space:pre-wrap;\">No npm run yet.</pre>\n"
                + "      </div>\n"
                + "      <div class=\"card\" style=\"margin-bottom: 20px;\">\n"
                + "        <div class=\"card-title\">Confirm review</div>\n"
                + "        <label style=\"display:flex; gap:10px; align-items:flex-start; cursor:pointer; font-size:0.9rem;\">\n"
                + "          <input type=\"checkbox\" id=\"chk-vscode-reviewed\" onchange=\"onVsCodeReviewToggle()\" style=\"margin-top:4px;\">\n"
                + "          <span>I have reviewed this branch in VS Code. Enable Create PR to open a Pull Request (files will not be re-committed).</span>\n"
                + "        </label>\n"
                + "      </div>\n"
                + "      <div class=\"card\" style=\"margin-bottom: 20px; padding: 12px;\">\n"
                + "        <div style=\"display:flex; justify-content:space-between; align-items:center; margin-bottom:10px; padding: 0 4px;\">\n"
                + "          <div class=\"card-title\" style=\"margin:0; font-size:0.95rem;\">⚡ VS Code Web Workspace (<span id=\"vscode-branch-display\">feat/wknd-site</span>)</div>\n"
                + "          <div style=\"font-size:0.8rem; color:var(--text-muted);\" id=\"vscode-frame-hint\">Branch file editor — vscode.dev opens in a new tab</div>\n"
                + "        </div>\n"
                + "        <div id=\"vscode-frame-container\" style=\"position:relative; width:100%; height:720px; background:#1e1e1e; border-radius:6px; overflow:hidden; border:1px solid var(--surface-border);\">\n"
                + "          <div id=\"vscode-placeholder\" style=\"display:flex; flex-direction:column; align-items:center; justify-content:center; height:100%; color:#94a3b8; text-align:center; padding:20px;\">\n"
                + "            <div style=\"font-size:2.5rem; margin-bottom:12px;\">💻</div>\n"
                + "            <div style=\"font-size:1.1rem; font-weight:600; margin-bottom:6px; color:#f1f5f9;\">VS Code Web Workspace Ready</div>\n"
                + "            <p style=\"max-width:560px; font-size:0.85rem; line-height:1.6; color:#94a3b8; margin-bottom:18px;\">\n"
                + "              vscode.dev cannot run inside AEM (it blocks iframes). Load the branch file list here, edit and save to GitHub, or use <b>Open in New Tab</b> for the full vscode.dev editor.\n"
                + "            </p>\n"
                + "            <button class=\"btn btn-primary\" onclick=\"loadVsCodeFrame()\">⚡ Load branch workspace</button>\n"
                + "          </div>\n"
                + "          <div id=\"vscode-workspace\" class=\"ws-layout\" style=\"display:none;\">\n"
                + "            <aside class=\"ws-sidebar\"><div class=\"ws-tree-title\">Branch files</div><ul id=\"ws-file-tree\"></ul></aside>\n"
                + "            <div class=\"ws-main\"><div class=\"ws-toolbar\"><span id=\"ws-open-path\">Select a file</span><button type=\"button\" class=\"btn btn-outline\" onclick=\"saveWorkspaceFile()\">Save to branch</button></div>\n"
                + "            <div class=\"ws-editor-pane\"><pre id=\"ws-line-numbers\" class=\"ws-line-numbers\" aria-hidden=\"true\">1</pre><textarea id=\"ws-editor\" class=\"ws-editor\" spellcheck=\"false\" wrap=\"off\" oninput=\"syncWsLineNumbers()\" onscroll=\"syncWsLineScroll()\"></textarea></div></div>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"card\" style=\"margin-bottom: 20px;\">\n"
                + "        <div class=\"card-title\">🔍 Branch File Changes & CI Build Status</div>\n"
                + "        <div id=\"github-status-result\" style=\"font-size:0.88rem; color:var(--text-muted);\">No branch checked yet. Click \"Check CI & Changed Files\" above.</div>\n"
                + "      </div>\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">📤 Pull Request</div>\n"
                + "        <p style=\"color:var(--text-muted); font-size:0.85rem;\">Review file changes, ensure GitHub Actions CI passes, and verify your component models in VS Code above before opening the official PR.</p>\n"
                + "        <button id=\"btn-create-pr\" class=\"btn btn-accent\" onclick=\"createPullRequest()\">📤 Open Pull Request</button>\n"
                + "        <div id=\"github-pr-result\" style=\"margin-top:10px;\"></div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "\n"
                + "  <div id=\"toast\" class=\"toast\"></div>\n"
                + "\n";
    }

    private static String htmlScript() {
        return ""
                + "  <script>\n"
                + "    let currentProjectId = 'wknd-site';\n"
                + "    let projectsList = [];\n"
                + "    let vscodeReviewConfirmed = false;\n"
                + "\n"
                + "    let csrfTokenPromise = null;\n"
                + "    function getCsrfToken() {\n"
                + "      if (!csrfTokenPromise) {\n"
                + "        csrfTokenPromise = fetch('/libs/granite/csrf/token.json').then(r => r.json()).then(d => (d && d.token) ? d.token : '').catch(() => '');\n"
                + "      }\n"
                + "      return csrfTokenPromise;\n"
                + "    }\n"
                + "    const api = async (path, opts = {}) => {\n"
                + "      const cleanPath = path.startsWith('/') ? path.substring(1) : path;\n"
                + "      const url = '/bin/aem-eds-modernizer/api?path=' + encodeURIComponent(cleanPath);\n"
                + "      const headers = Object.assign({ 'Content-Type': 'application/json' }, opts.headers || {});\n"
                + "      if (opts.method && String(opts.method).toUpperCase() !== 'GET') {\n"
                + "        const token = await getCsrfToken();\n"
                + "        if (token) headers['CSRF-Token'] = token;\n"
                + "      }\n"
                + "      opts.headers = headers;\n"
                + "      const res = await fetch(url, opts);\n"
                + "      const text = await res.text();\n"
                + "      let data = {};\n"
                + "      try { data = text ? JSON.parse(text) : {}; } catch (e) { throw new Error('HTTP ' + res.status + ': ' + (text || '').substring(0, 200)); }\n"
                + "      if (!res.ok) throw new Error(data.error || ('HTTP ' + res.status));\n"
                + "      return data;\n"
                + "    };\n"
                + "\n"
                + "    function showToast(msg) {\n"
                + "      const t = document.getElementById('toast');\n"
                + "      t.innerText = msg;\n"
                + "      t.classList.add('show');\n"
                + "      setTimeout(() => t.classList.remove('show'), 3500);\n"
                + "    }\n"
                + "\n"
                + "    function showTab(tabId) {\n"
                + "      document.querySelectorAll('.nav-tab').forEach(t => t.classList.remove('active'));\n"
                + "      document.querySelectorAll('.tab-content').forEach(c => c.style.display = 'none');\n"
                + "      const btn = Array.from(document.querySelectorAll('.nav-tab')).find(b => b.getAttribute('onclick') && b.getAttribute('onclick').includes(tabId));\n"
                + "      if (btn) btn.classList.add('active');\n"
                + "      const target = document.getElementById('tab-' + tabId);\n"
                + "      if (target) target.style.display = 'block';\n"
                + "      if (tabId === 'github') {\n"
                + "        const input = document.getElementById('github-branch-input');\n"
                + "        if (input && !input.value) input.value = `feat/${currentProjectId}`;\n"
                + "        const branchDisplay = document.getElementById('vscode-branch-display');\n"
                + "        if (branchDisplay && input) branchDisplay.innerText = input.value || `feat/${currentProjectId}`;\n"
                + "        const newTabBtn = document.getElementById('btn-open-vscode-newtab');\n"
                + "        if (newTabBtn) {\n"
                + "          newTabBtn.href = getVsCodeUrlForBranch(input ? input.value : `feat/${currentProjectId}`);\n"
                + "          newTabBtn.style.display = 'inline-flex';\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    function setPipelineStep(stepId, state) {\n"
                + "      const el = document.getElementById('step-' + stepId);\n"
                + "      if (el) {\n"
                + "        if (state === 'done') { el.className = 'step-item done'; }\n"
                + "        else if (state === 'active') { el.className = 'step-item active'; }\n"
                + "        else { el.className = 'step-item'; }\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    function log(agent, msg) {\n"
                + "      const term = document.getElementById('terminal');\n"
                + "      const time = new Date().toLocaleTimeString();\n"
                + "      const line = `<div class=\"log-line\"><span class=\"log-time\">[${time}]</span><span class=\"log-agent\">[${agent}]</span><span>${msg}</span></div>`;\n"
                + "      if (term) { term.innerHTML += line; term.scrollTop = term.scrollHeight; }\n"
                + "    }\n"
                + "\n"
                + "    function onProviderChange() {\n"
                + "      const provider = document.getElementById('cfg-aiProvider').value;\n"
                + "      const modelInput = document.getElementById('cfg-aiModel');\n"
                + "      const cloudBanner = document.getElementById('cloud-api-banner');\n"
                + "      const cloudTitle = document.getElementById('cloud-api-banner-title');\n"
                + "      const cloudKeyRef = document.getElementById('cloud-api-key-ref');\n"
                + "      const cloudKeyRefs = { anthropic: 'env:ANTHROPIC_API_KEY', openai: 'env:OPENAI_API_KEY', gemini: 'env:GEMINI_API_KEY' };\n"
                + "      const cloudLabels = { anthropic: 'Anthropic Claude', openai: 'OpenAI GPT', gemini: 'Google Gemini' };\n"
                + "      const isCloudApi = Object.prototype.hasOwnProperty.call(cloudKeyRefs, provider);\n"
                + "      if (cloudBanner) cloudBanner.style.display = isCloudApi ? 'block' : 'none';\n"
                + "      if (isCloudApi) {\n"
                + "        if (cloudTitle) cloudTitle.textContent = (cloudLabels[provider] || 'Cloud API') + ' — API key required';\n"
                + "        if (cloudKeyRef) cloudKeyRef.textContent = cloudKeyRefs[provider];\n"
                + "      }\n"
                + "      if (provider === 'anthropic') modelInput.value = 'claude-3-5-sonnet-20241022';\n"
                + "      else if (provider === 'openai') modelInput.value = 'gpt-4o';\n"
                + "      else if (provider === 'gemini') modelInput.value = 'gemini-1.5-pro';\n"
                + "      else if (provider === 'ollama') modelInput.value = 'qwen3:8b';\n"
                + "    }\n"
                + "\n"
                + "    function loadWkndPreset() {\n"
                + "      document.getElementById('cfg-id').value = 'wknd-site';\n"
                + "      document.getElementById('cfg-name').value = 'WKND Site Modernization';\n"
                + "      document.getElementById('cfg-authorUrl').value = 'http://localhost:4502';\n"
                + "      document.getElementById('cfg-publishUrl').value = 'http://localhost:4503';\n"
                + "      document.getElementById('cfg-contentRoot').value = '/content/wknd';\n"
                + "      document.getElementById('cfg-pageScope').value = '/content/wknd/*';\n"
                + "      document.getElementById('cfg-repoUrl').value = 'https://github.com/my-org/wknd-eds';\n"
                + "      document.getElementById('cfg-branch').value = 'main';\n"
                + "      document.getElementById('cfg-markerProp').value = 'edsModernize';\n"
                + "      document.getElementById('cfg-markerVal').value = 'true';\n"
                + "      document.getElementById('cfg-authoringStrategy').value = 'UNIVERSAL_EDITOR';\n"
                + "      document.getElementById('cfg-aiProvider').value = 'anthropic';\n"
                + "      document.getElementById('cfg-aiModel').value = 'claude-3-5-sonnet-20241022';\n"
                + "      document.getElementById('cfg-maxBudget').value = '100.00';\n"
                + "      document.getElementById('cfg-maxRepair').value = '5';\n"
                + "      onProviderChange();\n"
                + "      showToast('Loaded WKND Site Configuration Preset');\n"
                + "    }\n"
                + "\n"
                + "    function clearForm() {\n"
                + "      document.getElementById('cfg-id').value = 'project-' + Math.random().toString(36).substring(2,7);\n"
                + "      document.getElementById('cfg-name').value = '';\n"
                + "      document.getElementById('cfg-authorUrl').value = 'http://localhost:4502';\n"
                + "      document.getElementById('cfg-publishUrl').value = '';\n"
                + "      document.getElementById('cfg-contentRoot').value = '/content/';\n"
                + "      document.getElementById('cfg-pageScope').value = '';\n"
                + "      document.getElementById('cfg-repoUrl').value = '';\n"
                + "      document.getElementById('cfg-figmaUrl').value = '';\n"
                + "    }\n"
                + "\n"
                + "    async function saveProjectConfig() {\n"
                + "      const payload = {\n"
                + "        id: document.getElementById('cfg-id').value.trim() || 'project-1',\n"
                + "        name: document.getElementById('cfg-name').value.trim() || 'Untitled Project',\n"
                + "        aemAuthorUrl: document.getElementById('cfg-authorUrl').value.trim(),\n"
                + "        aemPublishUrl: document.getElementById('cfg-publishUrl').value.trim(),\n"
                + "        contentRoot: document.getElementById('cfg-contentRoot').value.trim(),\n"
                + "        pageScope: document.getElementById('cfg-pageScope').value.trim(),\n"
                + "        edsGitRepoUrl: document.getElementById('cfg-repoUrl').value.trim(),\n"
                + "        edsBranch: document.getElementById('cfg-branch').value.trim(),\n"
                + "        figmaUrl: document.getElementById('cfg-figmaUrl').value.trim(),\n"
                + "        markerProperty: document.getElementById('cfg-markerProp').value.trim(),\n"
                + "        markerValue: document.getElementById('cfg-markerVal').value.trim(),\n"
                + "        authoringStrategy: document.getElementById('cfg-authoringStrategy').value,\n"
                + "        aiProvider: document.getElementById('cfg-aiProvider').value,\n"
                + "        aiModel: document.getElementById('cfg-aiModel').value.trim(),\n"
                + "        maxBudgetUsd: parseFloat(document.getElementById('cfg-maxBudget').value) || 100.0,\n"
                + "        maxRepairAttempts: parseInt(document.getElementById('cfg-maxRepair').value, 10) || 5\n"
                + "      };\n"
                + "\n"
                + "      log('connection', `Saving project '${payload.name}' (${payload.id}) & verifying AEM endpoint...`);\n"
                + "      try {\n"
                + "        const saved = await api('projects', {\n"
                + "          method: 'POST',\n"
                + "          headers: { 'Content-Type': 'application/json' },\n"
                + "          body: JSON.stringify(payload)\n"
                + "        });\n"
                + "        currentProjectId = saved.id;\n"
                + "        log('connection', `Project saved successfully: ContentRoot=${payload.contentRoot}, EDS Repo=${payload.edsGitRepoUrl}`);\n"
                + "        showToast(`Project '${saved.name}' Saved & Connected!`);\n"
                + "        document.getElementById('btn-dryrun').disabled = false;\n"
                + "        setPipelineStep('connect', 'done');\n"
                + "        setPipelineStep('dryrun', 'active');\n"
                + "        await loadProjectsList();\n"
                + "        showTab('overview');\n"
                + "      } catch (err) {\n"
                + "        log('error', `Failed to save project: ${err.message}`);\n"
                + "        showToast('Error saving project');\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function loadProjectsList() {\n"
                + "      try {\n"
                + "        projectsList = await api('projects');\n"
                + "        const select = document.getElementById('project-select');\n"
                + "        if (projectsList && projectsList.length > 0) {\n"
                + "          select.innerHTML = projectsList.map(p => `<option value=\"${p.id}\" ${p.id === currentProjectId ? 'selected' : ''}>${p.name || p.id}</option>`).join('')\n"
                + "            + '<option value=\"new\">+ Create New Project...</option>';\n"
                + "        }\n"
                + "      } catch (e) { console.log(e); }\n"
                + "      const del = document.getElementById('btn-delete');\n"
                + "      if (del) del.disabled = !currentProjectId || currentProjectId === 'new';\n"
                + "    }\n"
                + "\n"
                + "    async function deleteCurrentProject() {\n"
                + "      if (!currentProjectId || currentProjectId === 'new') { showToast('Select a saved project first.'); return; }\n"
                + "      const p = (projectsList || []).find(x => x.id === currentProjectId);\n"
                + "      const label = p ? (p.name || p.id) : currentProjectId;\n"
                + "      if (!confirm('Delete project \"' + label + '\"?\\n\\nThis removes its saved config, jobs, inventory and generated blocks. This cannot be undone.')) return;\n"
                + "      try {\n"
                + "        await api('projects/' + encodeURIComponent(currentProjectId) + '/delete', { method: 'POST' });\n"
                + "        showToast('Project \\'' + label + '\\' deleted');\n"
                + "        projectsList = (projectsList || []).filter(x => x.id !== currentProjectId);\n"
                + "        currentProjectId = projectsList.length > 0 ? projectsList[0].id : 'wknd-site';\n"
                + "        await loadProjectsList();\n"
                + "        if (projectsList.length > 0) { await populateFormFromProject(currentProjectId); await refreshDashboard(); }\n"
                + "        showTab('overview');\n"
                + "      } catch (err) {\n"
                + "        log('error', 'Failed to delete project: ' + err.message);\n"
                + "        showToast('Error deleting project: ' + err.message);\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function onProjectSelectChange() {\n"
                + "      const val = document.getElementById('project-select').value;\n"
                + "      if (val === 'new') {\n"
                + "        clearForm();\n"
                + "        showTab('setup');\n"
                + "      } else {\n"
                + "        currentProjectId = val;\n"
                + "        await populateFormFromProject(val);\n"
                + "        await refreshDashboard();\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function populateFormFromProject(id) {\n"
                + "      const p = projectsList.find(x => x.id === id) || await api(`projects/${id}`);\n"
                + "      if (p) {\n"
                + "        document.getElementById('cfg-id').value = p.id || '';\n"
                + "        document.getElementById('cfg-name').value = p.name || '';\n"
                + "        document.getElementById('cfg-authorUrl').value = p.aemAuthorUrl || 'http://localhost:4502';\n"
                + "        document.getElementById('cfg-publishUrl').value = p.aemPublishUrl || '';\n"
                + "        document.getElementById('cfg-contentRoot').value = p.contentRoot || '/content/wknd';\n"
                + "        document.getElementById('cfg-pageScope').value = p.pageScope || '';\n"
                + "        document.getElementById('cfg-repoUrl').value = p.edsGitRepoUrl || '';\n"
                + "        document.getElementById('cfg-branch').value = p.edsBranch || 'main';\n"
                + "        document.getElementById('cfg-figmaUrl').value = p.figmaUrl || '';\n"
                + "        document.getElementById('cfg-markerProp').value = p.markerProperty || 'edsModernize';\n"
                + "        document.getElementById('cfg-markerVal').value = p.markerValue || 'true';\n"
                + "        document.getElementById('cfg-authoringStrategy').value = p.authoringStrategy || 'UNIVERSAL_EDITOR';\n"
                + "        document.getElementById('cfg-aiProvider').value = p.aiProvider || 'anthropic';\n"
                + "        document.getElementById('cfg-aiModel').value = p.aiModel || 'claude-3-5-sonnet-20241022';\n"
                + "        document.getElementById('cfg-maxBudget').value = p.maxBudgetUsd || 100.0;\n"
                + "        document.getElementById('cfg-maxRepair').value = p.maxRepairAttempts || 5;\n"
                + "        onProviderChange();\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function runDryRun() {\n"
                + "      document.getElementById('btn-dryrun').disabled = true;\n"
                + "      setPipelineStep('dryrun', 'active');\n"
                + "      log('orchestrator', `Starting Mandatory Dry Run for project '${currentProjectId}'...`);\n"
                + "      try {\n"
                + "        const job = await api(`projects/${currentProjectId}/dryrun`, { method: 'POST' });\n"
                + "        log('orchestrator', `Dry Run execution completed with state: ${job.state}`);\n"
                + "        setPipelineStep('dryrun', 'done');\n"
                + "        setPipelineStep('build', 'active');\n"
                + "        await refreshDashboard();\n"
                + "        document.getElementById('btn-migrate').disabled = false;\n"
                + "        showToast('Dry Run Completed! Review components, estimate & contract.');\n"
                + "      } catch (err) {\n"
                + "        log('error', `Dry run failed: ${err.message}`);\n"
                + "      } finally {\n"
                + "        document.getElementById('btn-dryrun').disabled = false;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    function resetVsCodeReviewGate() {\n"
                + "      vscodeReviewConfirmed = false;\n"
                + "      const chk = document.getElementById('chk-vscode-reviewed');\n"
                + "      if (chk) chk.checked = false;\n"
                + "      const btnPublish = document.getElementById('btn-publish');\n"
                + "      if (btnPublish) btnPublish.disabled = true;\n"
                + "    }\n"
                + "    function onVsCodeReviewToggle() {\n"
                + "      const chk = document.getElementById('chk-vscode-reviewed');\n"
                + "      vscodeReviewConfirmed = !!(chk && chk.checked);\n"
                + "      const btnPublish = document.getElementById('btn-publish');\n"
                + "      if (btnPublish) btnPublish.disabled = !vscodeReviewConfirmed;\n"
                + "      if (vscodeReviewConfirmed) { setPipelineStep('vscode', 'done'); setPipelineStep('publish', 'active'); }\n"
                + "    }\n"
                + "    function featureBranchName() { return 'feat/' + currentProjectId; }\n"
                + "    function applyPreviewBranch(branch) {\n"
                + "      const name = branch || featureBranchName();\n"
                + "      const input = document.getElementById('github-branch-input');\n"
                + "      if (input) input.value = name;\n"
                + "      const branchDisplay = document.getElementById('vscode-branch-display');\n"
                + "      if (branchDisplay) branchDisplay.innerText = name;\n"
                + "    }\n"
                + "    async function previewToBranch() {\n"
                + "      resetVsCodeReviewGate();\n"
                + "      setPipelineStep('validate', 'done');\n"
                + "      setPipelineStep('vscode', 'active');\n"
                + "      applyPreviewBranch(featureBranchName());\n"
                + "      log('preview', `Pushing generated files to branch '${featureBranchName()}' (no PR)...`);\n"
                + "      const job = await api(`projects/${currentProjectId}/preview`, { method: 'POST' });\n"
                + "      const meta = job.metadata || {};\n"
                + "      const branch = meta.branch || featureBranchName();\n"
                + "      applyPreviewBranch(branch);\n"
                + "      showTab('github');\n"
                + "      loadVsCodeFrame(meta.vscodeUrl || getVsCodeUrlForBranch(branch));\n"
                + "      setPipelineStep('vscode', 'done');\n"
                + "      setPipelineStep('publish', 'active');\n"
                + "      showToast('Branch pushed. Review in VS Code, then confirm to open the PR.');\n"
                + "      try { await checkBranchStatus(); } catch (e) {}\n"
                + "      return job;\n"
                + "    }\n"
                + "\n"
                + "    async function runMigration() {\n"
                + "      document.getElementById('btn-migrate').disabled = true;\n"
                + "      setPipelineStep('dryrun', 'done');\n"
                + "      setPipelineStep('build', 'active');\n"
                + "      log('orchestrator', `Executing Approved Migration pipeline for project '${currentProjectId}'...`);\n"
                + "      try {\n"
                + "        const job = await api(`projects/${currentProjectId}/migrate`, { method: 'POST' });\n"
                + "        log('orchestrator', `Migration finished with state: ${job.state}`);\n"
                + "        setPipelineStep('build', 'done');\n"
                + "        setPipelineStep('validate', 'done');\n"
                + "        await refreshDashboard();\n"
                + "        showToast('Blocks generated. Pushing preview branch for VS Code review...');\n"
                + "        try { await previewToBranch(); } catch (previewErr) {\n"
                + "          log('error', `Preview push failed: ${previewErr.message}`);\n"
                + "          showTab('github');\n"
                + "          showToast('Generate succeeded but branch push failed. Use Push Blocks & Open VS Code to retry.');\n"
                + "        }\n"
                + "      } catch (err) {\n"
                + "        log('error', `Migration failed: ${err.message}`);\n"
                + "      } finally {\n"
                + "        document.getElementById('btn-migrate').disabled = false;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function runPushToGit() {\n"
                + "      if (!vscodeReviewConfirmed) { showToast('Confirm you have reviewed the branch in VS Code first.'); showTab('github'); return; }\n"
                + "      const btnPublish = document.getElementById('btn-publish');\n"
                + "      if (btnPublish) btnPublish.disabled = true;\n"
                + "      setPipelineStep('publish', 'active');\n"
                + "      try {\n"
                + "        const job = await api(`projects/${currentProjectId}/publish`, { method: 'POST' });\n"
                + "        const prUrl = (job.metadata && job.metadata.prUrl) || job.prUrl;\n"
                + "        setPipelineStep('publish', 'done');\n"
                + "        const resultEl = document.getElementById('github-pr-result');\n"
                + "        if (resultEl && prUrl) resultEl.innerHTML = `<a href=\"${prUrl}\" target=\"_blank\">Pull Request opened: ${prUrl}</a>`;\n"
                + "        showToast(prUrl ? 'Pull Request opened against the review branch.' : 'Publish job completed.');\n"
                + "      } catch (err) {\n"
                + "        showToast('Error opening PR: ' + err.message);\n"
                + "      } finally {\n"
                + "        if (btnPublish) btnPublish.disabled = !vscodeReviewConfirmed;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    function encodeBranchSegments(branch) { return String(branch || 'main').split('/').map(encodeURIComponent).join('/'); }\n"
                + "    let workspaceOpenPath = '';\n"
                + "    function syncWsLineNumbers() {\n"
                + "      const editor = document.getElementById('ws-editor');\n"
                + "      const gutter = document.getElementById('ws-line-numbers');\n"
                + "      if (!editor || !gutter) return;\n"
                + "      const text = editor.value || '';\n"
                + "      const count = text.split(/\\r\\n|\\r|\\n/).length;\n"
                + "      let lines = '';\n"
                + "      for (let i = 1; i <= count; i++) { lines += i + (i === count ? '' : '\\n'); }\n"
                + "      gutter.textContent = lines || '1';\n"
                + "      syncWsLineScroll();\n"
                + "    }\n"
                + "    function syncWsLineScroll() {\n"
                + "      const editor = document.getElementById('ws-editor');\n"
                + "      const gutter = document.getElementById('ws-line-numbers');\n"
                + "      if (editor && gutter) gutter.scrollTop = editor.scrollTop;\n"
                + "    }\n"
                + "    function getVsCodeUrlForBranch(branch) {\n"
                + "      const repoInput = document.getElementById('cfg-repoUrl');\n"
                + "      let repoUrl = repoInput ? repoInput.value.trim() : '';\n"
                + "      if (!repoUrl) {\n"
                + "        const activePrj = projectsList.find(p => p.id === currentProjectId);\n"
                + "        if (activePrj && activePrj.edsGitRepoUrl) { repoUrl = activePrj.edsGitRepoUrl; }\n"
                + "      }\n"
                + "      if (!repoUrl) repoUrl = 'https://github.com/my-org/wknd-eds';\n"
                + "      let cleaned = repoUrl.trim();\n"
                + "      if (cleaned.endsWith('.git')) cleaned = cleaned.substring(0, cleaned.length - 4);\n"
                + "      if (cleaned.endsWith('/')) cleaned = cleaned.substring(0, cleaned.length - 1);\n"
                + "      if (cleaned.startsWith('https://github.com/')) {\n"
                + "        const ownerRepo = cleaned.substring('https://github.com/'.length);\n"
                + "        return `https://vscode.dev/github/${ownerRepo}/tree/${encodeBranchSegments(branch || 'feat/' + currentProjectId)}`;\n"
                + "      }\n"
                + "      return 'https://vscode.dev';\n"
                + "    }\n"
                + "    function loadVsCodeFrame(customUrl) {\n"
                + "      const input = document.getElementById('github-branch-input');\n"
                + "      const branch = (input && input.value.trim()) || `feat/${currentProjectId}`;\n"
                + "      const url = customUrl || getVsCodeUrlForBranch(branch);\n"
                + "      const placeholder = document.getElementById('vscode-placeholder');\n"
                + "      const workspace = document.getElementById('vscode-workspace');\n"
                + "      const newTabBtn = document.getElementById('btn-open-vscode-newtab');\n"
                + "      const branchDisplay = document.getElementById('vscode-branch-display');\n"
                + "      const hint = document.getElementById('vscode-frame-hint');\n"
                + "      if (branchDisplay) branchDisplay.innerText = branch;\n"
                + "      if (newTabBtn) { newTabBtn.href = url; newTabBtn.style.display = 'inline-flex'; }\n"
                + "      if (hint) hint.textContent = 'In-dashboard editor (vscode.dev cannot be embedded in AEM)';\n"
                + "      if (placeholder) placeholder.style.display = 'none';\n"
                + "      if (workspace) workspace.style.display = 'flex';\n"
                + "      loadWorkspaceFiles(branch);\n"
                + "    }\n"
                + "    function reloadVsCodeFrame() { loadVsCodeFrame(); showToast('Reloaded branch workspace'); }\n"
                + "    async function loadWorkspaceFiles(branch) {\n"
                + "      const tree = document.getElementById('ws-file-tree');\n"
                + "      if (!tree) return;\n"
                + "      tree.innerHTML = '<li class=\"ws-tree-empty\">Loading files…</li>';\n"
                + "      try {\n"
                + "        const data = await api(`projects/${currentProjectId}/workspace`, { method: 'POST', body: JSON.stringify({ branch }) });\n"
                + "        const files = data.files || [];\n"
                + "        if (!files.length) { tree.innerHTML = '<li class=\"ws-tree-empty\">No changed files yet. Push the preview branch first.</li>'; return; }\n"
                + "        tree.innerHTML = files.map(f => `<li class=\"ws-file-row\"><button type=\"button\" class=\"ws-file-btn\" data-path=\"${f.path}\">${f.path}</button><button type=\"button\" class=\"ws-file-del\" data-path=\"${f.path}\">Delete</button></li>`).join('');\n"
                + "        if (!tree.dataset.bound) {\n"
                + "          tree.dataset.bound = '1';\n"
                + "          tree.addEventListener('click', function(ev) {\n"
                + "            const del = ev.target.closest('.ws-file-del');\n"
                + "            const open = ev.target.closest('.ws-file-btn');\n"
                + "            if (del && del.dataset.path) { ev.preventDefault(); deleteWorkspaceFile(del.dataset.path); return; }\n"
                + "            if (open && open.dataset.path) openWorkspaceFile(open.dataset.path);\n"
                + "          });\n"
                + "        }\n"
                + "        const keepOpen = workspaceOpenPath && files.some(f => f.path === workspaceOpenPath);\n"
                + "        if (keepOpen) await openWorkspaceFile(workspaceOpenPath);\n"
                + "        else if (files[0] && files[0].path) await openWorkspaceFile(files[0].path);\n"
                + "      } catch (err) { tree.innerHTML = `<li class=\"ws-tree-empty\">${err.message}</li>`; }\n"
                + "    }\n"
                + "    async function openWorkspaceFile(path) {\n"
                + "      const input = document.getElementById('github-branch-input');\n"
                + "      const branch = (input && input.value.trim()) || `feat/${currentProjectId}`;\n"
                + "      const editor = document.getElementById('ws-editor');\n"
                + "      const label = document.getElementById('ws-open-path');\n"
                + "      workspaceOpenPath = path;\n"
                + "      if (label) label.textContent = path;\n"
                + "      document.querySelectorAll('.ws-file-btn').forEach(btn => btn.classList.toggle('active', btn.getAttribute('data-path') === path));\n"
                + "      if (editor) editor.value = 'Loading…';\n"
                + "      try {\n"
                + "        const data = await api(`projects/${currentProjectId}/workspace/file`, { method: 'POST', body: JSON.stringify({ branch, path }) });\n"
                + "        if (editor) { editor.value = data.content || ''; editor.readOnly = !!data.readOnly; }\n"
                + "        syncWsLineNumbers();\n"
                + "      } catch (err) { if (editor) editor.value = err.message; syncWsLineNumbers(); }\n"
                + "    }\n"
                + "    async function saveWorkspaceFile() {\n"
                + "      const input = document.getElementById('github-branch-input');\n"
                + "      const branch = (input && input.value.trim()) || `feat/${currentProjectId}`;\n"
                + "      const editor = document.getElementById('ws-editor');\n"
                + "      if (!workspaceOpenPath || !editor) { showToast('Open a file first.'); return; }\n"
                + "      try {\n"
                + "        const saved = await api(`projects/${currentProjectId}/workspace/save`, { method: 'POST', body: JSON.stringify({ branch, path: workspaceOpenPath, content: editor.value }) });\n"
                + "        if (saved && typeof saved.content === 'string') editor.value = saved.content; else await openWorkspaceFile(workspaceOpenPath);\n"
                + "        syncWsLineNumbers();\n"
                + "        showToast('Committed ' + workspaceOpenPath + ' on ' + branch);\n"
                + "      } catch (err) { showToast('Save failed: ' + err.message); }\n"
                + "    }\n"
                + "    async function deleteWorkspaceFile(path) {\n"
                + "      const input = document.getElementById('github-branch-input');\n"
                + "      const branch = (input && input.value.trim()) || `feat/${currentProjectId}`;\n"
                + "      const target = path || workspaceOpenPath;\n"
                + "      if (!target) { showToast('Select a file first.'); return; }\n"
                + "      if (!window.confirm('Delete ' + target + ' from ' + branch + '? This creates a new commit.')) return;\n"
                + "      try {\n"
                + "        await api(`projects/${currentProjectId}/workspace/delete`, { method: 'POST', body: JSON.stringify({ branch, path: target }) });\n"
                + "        if (workspaceOpenPath === target) { workspaceOpenPath = ''; const editor = document.getElementById('ws-editor'); const label = document.getElementById('ws-open-path'); if (editor) editor.value = ''; if (label) label.textContent = 'Select a file'; syncWsLineNumbers(); }\n"
                + "        showToast('Deleted ' + target + ' from ' + branch);\n"
                + "        await loadWorkspaceFiles(branch);\n"
                + "      } catch (err) { showToast('Delete failed: ' + err.message); }\n"
                + "    }\n"
                + "\n"
                + "    async function pushBlocksAndOpenVsCode() {\n"
                + "      const btn = document.getElementById('btn-push-blocks-tab');\n"
                + "      if (btn) btn.disabled = true;\n"
                + "      showToast('🚀 Pushing generated blocks to branch...');\n"
                + "      try {\n"
                + "        await previewToBranch();\n"
                + "        showToast('✅ Blocks pushed to branch & VS Code workspace loaded!');\n"
                + "      } catch (err) {\n"
                + "        showToast('⚠️ Push failed: ' + err.message);\n"
                + "      } finally {\n"
                + "        if (btn) btn.disabled = false;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function checkBranchStatus() {\n"
                + "      const branch = document.getElementById('github-branch-input').value.trim();\n"
                + "      const resultEl = document.getElementById('github-status-result');\n"
                + "      if (!branch) { showToast('Enter a branch name first.'); return; }\n"
                + "      resultEl.innerHTML = 'Checking CI runs and changed files...';\n"
                + "      try {\n"
                + "        const data = await api(`projects/${currentProjectId}/branch-status`, {\n"
                + "          method: 'POST',\n"
                + "          headers: { 'Content-Type': 'application/json' },\n"
                + "          body: JSON.stringify({ branch })\n"
                + "        });\n"
                + "        if (data.error) { resultEl.innerHTML = `<span style=\"color:var(--danger,#c00)\">${data.error}</span>`; return; }\n"
                + "        let html = '';\n"
                + "        if (data.vscodeUrl) {\n"
                + "          html += `<p><a href=\"${data.vscodeUrl}\" target=\"_blank\">🔗 Open branch '${data.branch}' in vscode.dev</a></p>`;\n"
                + "          loadVsCodeFrame(data.vscodeUrl);\n"
                + "        }\n"
                + "        if (data.latestRun) {\n"
                + "          const r = data.latestRun;\n"
                + "          html += `<p><b>Latest CI run:</b> ${r.name || 'workflow'} — status: <b>${r.status}</b>, conclusion: <b style=\"color:${r.conclusion === 'success' ? 'var(--accent)' : 'var(--warn)'}\">${r.conclusion || 'pending'}</b> `\n"
                + "               + (r.htmlUrl ? `(<a href=\"${r.htmlUrl}\" target=\"_blank\">view run logs</a>)` : '') + `</p>`;\n"
                + "        } else {\n"
                + "          html += '<p><i>No GitHub Actions workflow run found for this branch (CI may not be configured on the repo, or no run has triggered yet).</i></p>';\n"
                + "        }\n"
                + "        const files = data.changedFiles || [];\n"
                + "        html += `<p><b>Changed files vs '${data.baseBranch}':</b> ${files.length}</p>`;\n"
                + "        if (files.length) {\n"
                + "          html += '<table><thead><tr><th>File</th><th>Status</th><th>+/-</th></tr></thead><tbody>';\n"
                + "          files.forEach(f => {\n"
                + "            html += `<tr><td><code>${f.filename}</code></td><td><span style=\"font-weight:700;\">${f.status}</span></td><td><span style=\"color:var(--accent);\">+${f.additions}</span> / <span style=\"color:var(--danger);\">${f.deletions}</span></td></tr>`;\n"
                + "          });\n"
                + "          html += '</tbody></table>';\n"
                + "        }\n"
                + "        resultEl.innerHTML = html;\n"
                + "      } catch (err) {\n"
                + "        resultEl.innerHTML = `<span style=\"color:var(--danger,#c00)\">Check failed: ${err.message}</span>`;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function createPullRequest() {\n"
                + "      if (!vscodeReviewConfirmed) { showToast('Confirm you have reviewed the branch in VS Code first.'); return; }\n"
                + "      const confirmed = confirm('Open a Pull Request from ' + featureBranchName() + ' for project ' + currentProjectId + '? Generated files will not be re-committed.');\n"
                + "      if (!confirmed) { return; }\n"
                + "      await runPushToGit();\n"
                + "    }\n"
                + "\n"
                + "    async function runNpmScript(command) {\n"
                + "      const logEl = document.getElementById('npm-log-terminal');\n"
                + "      const lintBtn = document.getElementById('btn-npm-lint');\n"
                + "      const jsonBtn = document.getElementById('btn-npm-json');\n"
                + "      const healBtn = document.getElementById('btn-npm-heal');\n"
                + "      if (lintBtn) lintBtn.disabled = true;\n"
                + "      if (jsonBtn) jsonBtn.disabled = true;\n"
                + "      if (healBtn) healBtn.disabled = true;\n"
                + "      if (logEl) logEl.textContent = (command === 'heal' ? '$ Heal CI' : ('$ npm run ' + command)) + '\\nDispatching GitHub Actions...\\n';\n"
                + "      try {\n"
                + "        const started = await api(`projects/${currentProjectId}/npm`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ command }) });\n"
                + "        if (started.error) { if (logEl) logEl.textContent += 'ERROR: ' + started.error + '\\n'; return; }\n"
                + "        if (started.logs && logEl) logEl.textContent = started.logs;\n"
                + "        if (command === 'heal') { if (logEl) logEl.textContent += 'Heal loop ' + (started.status || 'started') + (started.ciHeal ? (' (' + started.ciHeal + ')') : '') + '.\\n'; showToast('Heal CI: ' + (started.ciHeal || started.status || 'started')); return; }\n"
                + "        if (!started.runId) { if (logEl) logEl.textContent += 'Dispatched.\\n'; return; }\n"
                + "        if (started.status === 'completed') { showToast('npm run ' + command + ': ' + (started.conclusion || started.status)); return; }\n"
                + "        for (let i = 0; i < 40; i++) {\n"
                + "          await new Promise(r => setTimeout(r, 2500));\n"
                + "          const data = await api(`projects/${currentProjectId}/npm/${encodeURIComponent(started.runId)}`);\n"
                + "          if (data.logs) logEl.textContent = data.logs;\n"
                + "          if (data.status === 'completed' || data.status === 'failure' || data.status === 'cancelled') {\n"
                + "            showToast('npm run ' + command + ': ' + (data.conclusion || data.status));\n"
                + "            break;\n"
                + "          }\n"
                + "        }\n"
                + "      } catch (err) {\n"
                + "        if (logEl) logEl.textContent += 'ERROR: ' + err.message + '\\n';\n"
                + "      } finally {\n"
                + "        if (lintBtn) lintBtn.disabled = false;\n"
                + "        if (jsonBtn) jsonBtn.disabled = false;\n"
                + "        if (healBtn) healBtn.disabled = false;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    async function refreshDashboard() {\n"
                + "      try {\n"
                + "        const inv = await api(`projects/${currentProjectId}/inventory`);\n"
                + "        if (inv && inv.pages) {\n"
                + "          document.getElementById('stat-pages').innerText = inv.pages.length;\n"
                + "          document.getElementById('stat-eligible').innerText = (inv.eligiblePages || inv.pages.length) + ' eligible';\n"
                + "          document.getElementById('stat-components').innerText = inv.components ? inv.components.length : 0;\n"
                + "          renderPagesTable(inv.pages);\n"
                + "          renderComponentsTable(inv.components);\n"
                + "          if (inv.pages.length && document.getElementById('btn-migrate')) document.getElementById('btn-migrate').disabled = false;\n"
                + "        }\n"
                + "      } catch (e) {}\n"
                + "      if (typeof loadPreviewArtifacts === 'function') { try { await loadPreviewArtifacts(); } catch (e) {} }\n"
                + "      try {\n"
                + "        const jobs = await api(`projects/${currentProjectId}/jobs`);\n"
                + "        if (Array.isArray(jobs) && jobs.length && jobs[0].state && jobs[0].state !== 'DISCOVERING' && jobs[0].state !== 'PLANNED') {\n"
                + "          if (document.getElementById('btn-migrate')) document.getElementById('btn-migrate').disabled = false;\n"
                + "        }\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const plan = await api(`projects/${currentProjectId}/plan`);\n"
                + "        if (plan) {\n"
                + "          document.getElementById('stat-cost').innerText = '$' + (plan.costExpected || 0).toFixed(2);\n"
                + "          document.getElementById('stat-requests').innerText = (plan.aiRequestsExpected || 0) + ' AI calls estimated';\n"
                + "          document.getElementById('stat-time').innerText = (plan.timeExpectedSec || 0) + 's';\n"
                + "          document.getElementById('stat-range').innerText = `Lo: ${(plan.timeOptimisticSec||0)}s | Hi: ${(plan.timePessimisticSec||0)}s`;\n"
                + "          if (plan.derivationTrail) {\n"
                + "            const trail = document.getElementById('estimate-trail');\n"
                + "            trail.innerHTML = plan.derivationTrail.map(s => '<li>' + String(s).replace(/</g,'&lt;') + '</li>').join('');\n"
                + "          }\n"
                + "        }\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const redirects = await api(`projects/${currentProjectId}/redirects`);\n"
                + "        renderRedirectsTable(redirects);\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const deps = await api(`projects/${currentProjectId}/dependencies`);\n"
                + "        renderDependenciesTable(deps);\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const rollout = await api(`projects/${currentProjectId}/rollout-stages`);\n"
                + "        renderRolloutTable(rollout);\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const repairs = await api(`projects/${currentProjectId}/repairs`);\n"
                + "        renderRepairsTable(repairs);\n"
                + "      } catch (e) {}\n"
                + "\n"
                + "      try {\n"
                + "        const benchmarks = await api(`projects/${currentProjectId}/benchmarks`);\n"
                + "        renderBenchmarksTable(benchmarks);\n"
                + "      } catch (e) {}\n"
                + "    }\n"
                + "\n"
                + "    function renderPagesTable(pages) {\n"
                + "      if (typeof renderPagesPreview === 'function') { renderPagesPreview(pages); return; }\n"
                + "      const tbody = document.querySelector('#table-pages tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (pages && pages.length > 0)\n"
                + "        ? pages.map(p => `<tr><td><code>${p.path}</code></td><td>${p.title || '-'}</td><td>${p.template || '-'}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"3\">No pages discovered yet.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderComponentsTable(components) {\n"
                + "      const list = document.getElementById('table-components');\n"
                + "      if (!list) return;\n"
                + "      list.innerHTML = (components && components.length > 0)\n"
                + "        ? components.map(c => `<li class=\"data-list-item\"><div><div class=\"data-list-title\">${c.title || c.proposedEdsBlock || 'Untitled'}</div><div class=\"data-list-meta\">${c.resourceType || '-'}</div></div><div><div class=\"data-list-block\">${c.proposedEdsBlock || '-'}</div></div></li>`).join('')\n"
                + "        : '<li class=\"data-list-empty\">No components analyzed yet.</li>';\n"
                + "    }\n"
                + "\n"
                + "    function renderRedirectsTable(list) {\n"
                + "      const tbody = document.querySelector('#table-redirects tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(r => `<tr><td><code>${r.sourceUrl}</code></td><td><code>${r.targetUrl}</code></td><td><span style=\"color:var(--accent); font-weight:700;\">${r.statusCode || 301}</span></td><td>${r.conflict ? '<span style=\"color:var(--warn);\">⚠️ Conflict</span>' : '<span style=\"color:var(--accent);\">OK</span>'}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No redirects mapped.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderDependenciesTable(list) {\n"
                + "      const tbody = document.querySelector('#table-dependencies tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(d => `<tr><td><code>${d.source}</code></td><td><code>${d.target}</code></td><td><span style=\"color:var(--primary);\">${d.edgeType}</span></td><td>${d.impactLevel || 'LOW'}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No dependencies computed.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderRolloutTable(list) {\n"
                + "      const tbody = document.querySelector('#table-rollout tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(s => `<tr><td>#${s.stageIndex}</td><td><b>${s.stageName}</b></td><td><span style=\"color:var(--accent); font-weight:700;\">${s.targetTrafficPercent}%</span></td><td>${s.status}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No rollout stages initialized.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderRepairsTable(list) {\n"
                + "      const tbody = document.querySelector('#table-repairs tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(r => `<tr><td><code>${r.targetPath}</code></td><td>#${r.attemptNumber}</td><td>${r.issueCategory || 'STYLE'}</td><td>${r.successful ? '<span style=\"color:var(--accent);\">✅ Fixed</span>' : '<span style=\"color:var(--danger);\">❌ Failed</span>'}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No repair attempts recorded.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderBenchmarksTable(list) {\n"
                + "      const tbody = document.querySelector('#table-benchmarks tbody');\n"
                + "      if (!tbody) return;\n"
                + "      tbody.innerHTML = (list && list.length > 0)\n"
                + "        ? list.map(b => `<tr><td><b>${b.agent}</b></td><td>${b.operation}</td><td>${b.durationMs}ms</td><td>${(b.costMicros || 0).toFixed(1)}</td></tr>`).join('')\n"
                + "        : '<tr><td colspan=\"4\">No benchmark samples recorded.</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function appendChat(role, text) {\n"
                + "      const box = document.getElementById('chat-messages');\n"
                + "      if (!box) return;\n"
                + "      const div = document.createElement('div');\n"
                + "      div.className = 'log-line';\n"
                + "      div.innerHTML = `<span class=\"log-agent\">[${role}]</span> <span>${text}</span>`;\n"
                + "      box.appendChild(div);\n"
                + "      box.scrollTop = box.scrollHeight;\n"
                + "    }\n"
                + "    async function sendChat() {\n"
                + "      const input = document.getElementById('chat-input');\n"
                + "      const message = input && input.value ? input.value.trim() : '';\n"
                + "      if (!message) return;\n"
                + "      if (/overview stream|show (me )?(the )?(live )?events/i.test(message)) {\n"
                + "        showTab('overview'); refreshDashboard();\n"
                + "        appendChat('agent', 'Opened Overview — activity stream is on this tab.');\n"
                + "        if (input) input.value = '';\n"
                + "        return;\n"
                + "      }\n"
                + "      appendChat('you', message);\n"
                + "      if (input) input.value = '';\n"
                + "      try {\n"
                + "        const res = await api(`projects/${currentProjectId}/chat`, {\n"
                + "          method: 'POST', body: JSON.stringify({ message: message, history: [] })\n"
                + "        });\n"
                + "        appendChat('agent', (res && res.reply) ? res.reply : '(empty reply)');\n"
                + "        if (res && res.steps) log('chat', 'tool steps: ' + JSON.stringify(res.steps));\n"
                + "      } catch (err) {\n"
                + "        appendChat('error', err.message || String(err));\n"
                + "      }\n"
                + "    }\n"
                + "    function quickChat(msg) {\n"
                + "      const input = document.getElementById('chat-input');\n"
                + "      if (input) input.value = msg;\n"
                + "      sendChat();\n"
                + "    }\n"
                + "\n"
                + "    window.addEventListener('load', async () => {\n"
                + "      try {\n"
                + "        await loadProjectsList();\n"
                + "        if (projectsList && projectsList.length > 0) {\n"
                + "          currentProjectId = projectsList[0].id;\n"
                + "          await populateFormFromProject(currentProjectId);\n"
                + "          await refreshDashboard();\n"
                + "        } else {\n"
                + "          onProviderChange();\n"
                + "        }\n"
                + "      } catch (e) {\n"
                + "        console.log('Dashboard init:', e);\n"
                + "      }\n"
                + "    });\n"
                + "  </script>\n"
                + "</body>\n"
                + "</html>\n";
    }

    /** Breaks javac's 64KB string-constant folding for this generated page. */
    private static String runtimeJoin() {
        return new String();
    }
}
