package com.adobe.aem.modernizer.dashboard;

/**
 * Generates the self-contained, inlined Modernizer Dashboard SPA (Master §3, §31, ADR 0002).
 */
public final class StaticDashboard {

    private StaticDashboard() {}

    public static String html() {
        return html("/bin/aem-eds-modernizer/api");
    }

    public static String html(String apiBase) {
        String base = (apiBase == null || apiBase.trim().isEmpty())
                ? "/bin/aem-eds-modernizer/api" : apiBase.trim();
        if (!base.endsWith("/")) {
            base += "/";
        }

        return "<!doctype html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <title>AEM → EDS Modernizer</title>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
                + "  <base href=\"" + base + "\">\n"
                + "  <style>\n"
                + "    :root {\n"
                + "      --bg-dark: #0f172a;\n"
                + "      --surface: #1e293b;\n"
                + "      --surface-border: #334155;\n"
                + "      --primary: #38bdf8;\n"
                + "      --primary-hover: #0ea5e9;\n"
                + "      --accent: #10b981;\n"
                + "      --warn: #f59e0b;\n"
                + "      --danger: #ef4444;\n"
                + "      --text: #f8fafc;\n"
                + "      --text-muted: #94a3b8;\n"
                + "      --font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;\n"
                + "      --font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;\n"
                + "    }\n"
                + "    * { box-sizing: border-box; margin: 0; padding: 0; }\n"
                + "    body { background: var(--bg-dark); color: var(--text); font-family: var(--font-sans); min-height: 100vh; display: flex; flex-direction: column; }\n"
                + "    header { background: rgba(30,41,59,0.85); backdrop-filter: blur(8px); border-bottom: 1px solid var(--surface-border); padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; position: sticky; top: 0; z-index: 100; }\n"
                + "    .brand { display: flex; align-items: center; gap: 12px; font-size: 1.25rem; font-weight: 700; color: var(--text); }\n"
                + "    .brand svg { fill: var(--primary); }\n"
                + "    .status-badge { display: inline-flex; align-items: center; gap: 6px; padding: 4px 10px; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; background: rgba(16,185,129,0.15); color: var(--accent); border: 1px solid rgba(16,185,129,0.3); }\n"
                + "    .container { max-width: 1400px; margin: 0 auto; padding: 24px; width: 100%; flex: 1; }\n"
                + "    .nav-tabs { display: flex; gap: 8px; border-bottom: 1px solid var(--surface-border); margin-bottom: 24px; overflow-x: auto; }\n"
                + "    .nav-tab { padding: 10px 18px; border: none; background: transparent; color: var(--text-muted); font-size: 0.9rem; font-weight: 600; cursor: pointer; border-bottom: 2px solid transparent; transition: all 0.2s; white-space: nowrap; }\n"
                + "    .nav-tab:hover { color: var(--text); }\n"
                + "    .nav-tab.active { color: var(--primary); border-bottom-color: var(--primary); }\n"
                + "    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; margin-bottom: 24px; }\n"
                + "    .card { background: var(--surface); border: 1px solid var(--surface-border); border-radius: 8px; padding: 20px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }\n"
                + "    .card-title { font-size: 0.85rem; font-weight: 600; text-transform: uppercase; color: var(--text-muted); margin-bottom: 8px; }\n"
                + "    .card-val { font-size: 1.8rem; font-weight: 700; color: var(--text); }\n"
                + "    .card-sub { font-size: 0.8rem; color: var(--text-muted); margin-top: 4px; }\n"
                + "    .btn { display: inline-flex; align-items: center; justify-content: center; gap: 8px; padding: 10px 20px; border-radius: 6px; font-weight: 600; font-size: 0.9rem; cursor: pointer; border: none; transition: all 0.2s; text-decoration: none; }\n"
                + "    .btn-primary { background: var(--primary); color: #0f172a; }\n"
                + "    .btn-primary:hover { background: var(--primary-hover); }\n"
                + "    .btn-accent { background: var(--accent); color: #0f172a; }\n"
                + "    .btn-accent:hover { filter: brightness(1.1); }\n"
                + "    .btn-outline { background: transparent; border: 1px solid var(--surface-border); color: var(--text); }\n"
                + "    .btn-outline:hover { background: var(--surface); }\n"
                + "    .btn:disabled { opacity: 0.5; cursor: not-allowed; }\n"
                + "    .actions { display: flex; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; }\n"
                + "    table { width: 100%; border-collapse: collapse; text-align: left; font-size: 0.875rem; }\n"
                + "    th, td { padding: 12px 16px; border-bottom: 1px solid var(--surface-border); }\n"
                + "    th { color: var(--text-muted); font-weight: 600; background: rgba(15,23,42,0.4); }\n"
                + "    tr:hover td { background: rgba(255,255,255,0.02); }\n"
                + "    .log-terminal { background: #090d16; border: 1px solid var(--surface-border); border-radius: 6px; padding: 16px; font-family: var(--font-mono); font-size: 0.8rem; height: 320px; overflow-y: auto; color: #a5b4fc; }\n"
                + "    .log-line { margin-bottom: 4px; line-height: 1.5; }\n"
                + "    .log-time { color: var(--text-muted); margin-right: 8px; }\n"
                + "    .log-agent { color: var(--primary); font-weight: 600; margin-right: 8px; }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "  <header>\n"
                + "    <div class=\"brand\">\n"
                + "      <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path d=\"M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5\"/></svg>\n"
                + "      <span>AEM → EDS Modernizer</span>\n"
                + "    </div>\n"
                + "    <div id=\"system-status\" class=\"status-badge\">● OSGi Active (Mock Mode)</div>\n"
                + "  </header>\n"
                + "\n"
                + "  <div class=\"container\">\n"
                + "    <div class=\"actions\">\n"
                + "      <button id=\"btn-demo\" class=\"btn btn-outline\" onclick=\"createDemoProject()\">⚡ Create Demo Project (WKND)</button>\n"
                + "      <button id=\"btn-dryrun\" class=\"btn btn-primary\" onclick=\"runDryRun()\" disabled>🔍 Run Dry Run</button>\n"
                + "      <button id=\"btn-migrate\" class=\"btn btn-accent\" onclick=\"runMigration()\" disabled>🚀 Approve Contract & Migrate</button>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"nav-tabs\">\n"
                + "      <button class=\"nav-tab active\" onclick=\"showTab('overview')\">Overview</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('pages')\">Pages & Scope</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('components')\">Components & Blocks</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('estimate')\">Estimate & Cost</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('redirects')\">URL Redirects (Phase 2)</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('dependencies')\">Dependencies (Phase 2)</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('rollout')\">Rollout Stages (Phase 2)</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('repairs')\">Repairs (Phase 2)</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('benchmarks')\">Benchmarks (Phase 2)</button>\n"
                + "      <button class=\"nav-tab\" onclick=\"showTab('events')\">Live Events</button>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Overview -->\n"
                + "    <div id=\"tab-overview\" class=\"tab-content\">\n"
                + "      <div class=\"grid\">\n"
                + "        <div class=\"card\"><div class=\"card-title\">Total Pages</div><div class=\"card-val\" id=\"stat-pages\">0</div><div class=\"card-sub\" id=\"stat-eligible\">0 eligible</div></div>\n"
                + "        <div class=\"card\"><div class=\"card-title\">Components Discovered</div><div class=\"card-val\" id=\"stat-components\">0</div><div class=\"card-sub\">Mapped to EDS blocks</div></div>\n"
                + "        <div class=\"card\"><div class=\"card-title\">Expected AI Cost</div><div class=\"card-val\" id=\"stat-cost\">$0.00</div><div class=\"card-sub\" id=\"stat-requests\">0 AI calls</div></div>\n"
                + "        <div class=\"card\"><div class=\"card-title\">Estimated Duration</div><div class=\"card-val\" id=\"stat-time\">0s</div><div class=\"card-sub\">Lo: 0s | Hi: 0s</div></div>\n"
                + "      </div>\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Real-time Activity Stream</div>\n"
                + "        <div id=\"terminal\" class=\"log-terminal\">Waiting for project initialization...</div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Pages -->\n"
                + "    <div id=\"tab-pages\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\"><table id=\"table-pages\"><thead><tr><th>AEM Path</th><th>Title</th><th>Template</th><th>Eligible</th></tr></thead><tbody><tr><td colspan=\"4\">No pages discovered yet.</td></tr></tbody></table></div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Components -->\n"
                + "    <div id=\"tab-components\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\"><table id=\"table-components\"><thead><tr><th>Resource Type</th><th>Title</th><th>Group</th><th>Proposed EDS Block</th><th>Classification</th></tr></thead><tbody><tr><td colspan=\"5\">No components analyzed yet.</td></tr></tbody></table></div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Estimate -->\n"
                + "    <div id=\"tab-estimate\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\">\n"
                + "        <div class=\"card-title\">Derivation Trail & Cost Breakdown</div>\n"
                + "        <pre id=\"estimate-trail\" style=\"font-family:var(--font-mono); font-size:0.85rem; color:#38bdf8; line-height:1.6;\">Run a Dry Run to compute derivation trail.</pre>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Redirects -->\n"
                + "    <div id=\"tab-redirects\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\"><table id=\"table-redirects\"><thead><tr><th>Source URL</th><th>Target URL</th><th>Status</th><th>Conflict</th></tr></thead><tbody><tr><td colspan=\"4\">No redirects mapped.</td></tr></tbody></table></div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Dependencies -->\n"
                + "    <div id=\"tab-dependencies\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\"><table id=\"table-dependencies\"><thead><tr><th>Source Node</th><th>Target Node</th><th>Edge Type</th><th>Impact</th></tr></thead><tbody><tr><td colspan=\"4\">No dependencies computed.</td></tr></tbody></table></div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Rollout -->\n"
                + "    <div id=\"tab-rollout\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\"><table id=\"table-rollout\"><thead><tr><th>Stage</th><th>Name</th><th>Traffic %</th><th>Status</th></tr></thead><tbody><tr><td colspan=\"4\">No rollout stages initialized.</td></tr></tbody></table></div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Repairs -->\n"
                + "    <div id=\"tab-repairs\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\"><table id=\"table-repairs\"><thead><tr><th>Target File</th><th>Attempt #</th><th>Issue Category</th><th>Fix Status</th></tr></thead><tbody><tr><td colspan=\"4\">No repair attempts recorded.</td></tr></tbody></table></div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Benchmarks -->\n"
                + "    <div id=\"tab-benchmarks\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\"><table id=\"table-benchmarks\"><thead><tr><th>Agent</th><th>Operation</th><th>Duration (ms)</th><th>Cost (µ$)</th></tr></thead><tbody><tr><td colspan=\"4\">No benchmark samples recorded.</td></tr></tbody></table></div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Tab: Events -->\n"
                + "    <div id=\"tab-events\" class=\"tab-content\" style=\"display:none;\">\n"
                + "      <div class=\"card\"><div id=\"events-log\" class=\"log-terminal\" style=\"height:450px;\"></div></div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "\n"
                + "  <script>\n"
                + "    let currentProjectId = 'wknd-demo';\n"
                + "    const api = (path, opts) => {\n"
                + "      const base = (document.querySelector('base')||{}).href || '/bin/aem-eds-modernizer/api/';\n"
                + "      return fetch(base + path, opts).then(r => r.json());\n"
                + "    };\n"
                + "\n"
                + "    function showTab(tabId) {\n"
                + "      document.querySelectorAll('.nav-tab').forEach(t => t.classList.remove('active'));\n"
                + "      document.querySelectorAll('.tab-content').forEach(c => c.style.display = 'none');\n"
                + "      event.target.classList.add('active');\n"
                + "      document.getElementById('tab-' + tabId).style.display = 'block';\n"
                + "    }\n"
                + "\n"
                + "    function log(agent, msg) {\n"
                + "      const term = document.getElementById('terminal');\n"
                + "      const eventsLog = document.getElementById('events-log');\n"
                + "      const time = new Date().toLocaleTimeString();\n"
                + "      const line = `<div class=\"log-line\"><span class=\"log-time\">[${time}]</span><span class=\"log-agent\">[${agent}]</span><span>${msg}</span></div>`;\n"
                + "      term.innerHTML += line;\n"
                + "      eventsLog.innerHTML += line;\n"
                + "      term.scrollTop = term.scrollHeight;\n"
                + "      eventsLog.scrollTop = eventsLog.scrollHeight;\n"
                + "    }\n"
                + "\n"
                + "    async function createDemoProject() {\n"
                + "      log('system', 'Creating WKND Demo Project...');\n"
                + "      const p = await api('projects', {\n"
                + "        method: 'POST',\n"
                + "        headers: { 'Content-Type': 'application/json' },\n"
                + "        body: JSON.stringify({\n"
                + "          id: 'wknd-demo',\n"
                + "          name: 'WKND Site Modernization',\n"
                + "          aemAuthorUrl: 'https://mock-aem.local',\n"
                + "          contentRoot: '/content/wknd',\n"
                + "          edsGitRepoUrl: 'https://github.com/company/wknd-eds'\n"
                + "        })\n"
                + "      });\n"
                + "      currentProjectId = p.id;\n"
                + "      document.getElementById('btn-dryrun').disabled = false;\n"
                + "      log('system', 'Project initialized: ' + p.name + ' (' + p.id + ')');\n"
                + "    }\n"
                + "\n"
                + "    async function runDryRun() {\n"
                + "      document.getElementById('btn-dryrun').disabled = true;\n"
                + "      log('orchestrator', 'Starting Mandatory Dry Run...');\n"
                + "      const job = await api(`projects/${currentProjectId}/dryrun`, { method: 'POST' });\n"
                + "      log('orchestrator', 'Dry run completed with status: ' + job.state);\n"
                + "      await refreshDashboard();\n"
                + "      document.getElementById('btn-migrate').disabled = false;\n"
                + "    }\n"
                + "\n"
                + "    async function runMigration() {\n"
                + "      document.getElementById('btn-migrate').disabled = true;\n"
                + "      log('orchestrator', 'Executing Approved Migration...');\n"
                + "      const job = await api(`projects/${currentProjectId}/migrate`, { method: 'POST' });\n"
                + "      log('orchestrator', 'Migration finished with state: ' + job.state);\n"
                + "      await refreshDashboard();\n"
                + "    }\n"
                + "\n"
                + "    async function refreshDashboard() {\n"
                + "      const inv = await api(`projects/${currentProjectId}/inventory`);\n"
                + "      if (inv && inv.pages) {\n"
                + "        document.getElementById('stat-pages').innerText = inv.pages.length;\n"
                + "        document.getElementById('stat-eligible').innerText = inv.eligiblePages + ' eligible';\n"
                + "        document.getElementById('stat-components').innerText = inv.components ? inv.components.length : 0;\n"
                + "        renderPagesTable(inv.pages);\n"
                + "        renderComponentsTable(inv.components);\n"
                + "      }\n"
                + "\n"
                + "      const plan = await api(`projects/${currentProjectId}/plan`);\n"
                + "      if (plan) {\n"
                + "        document.getElementById('stat-cost').innerText = '$' + plan.costExpected.toFixed(2);\n"
                + "        document.getElementById('stat-requests').innerText = plan.aiRequestsExpected + ' AI calls';\n"
                + "        document.getElementById('stat-time').innerText = plan.timeExpectedSec + 's';\n"
                + "        if (plan.derivationTrail) {\n"
                + "          document.getElementById('estimate-trail').innerText = plan.derivationTrail.join('\\n');\n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      // Phase 2 loads\n"
                + "      const redirects = await api(`projects/${currentProjectId}/redirects`);\n"
                + "      renderRedirectsTable(redirects);\n"
                + "\n"
                + "      const deps = await api(`projects/${currentProjectId}/dependencies`);\n"
                + "      renderDependenciesTable(deps);\n"
                + "\n"
                + "      const rollout = await api(`projects/${currentProjectId}/rollout-stages`);\n"
                + "      renderRolloutTable(rollout);\n"
                + "\n"
                + "      const repairs = await api(`projects/${currentProjectId}/repairs`);\n"
                + "      renderRepairsTable(repairs);\n"
                + "\n"
                + "      const benchmarks = await api(`projects/${currentProjectId}/benchmarks`);\n"
                + "      renderBenchmarksTable(benchmarks);\n"
                + "    }\n"
                + "\n"
                + "    function renderPagesTable(pages) {\n"
                + "      const tbody = document.querySelector('#table-pages tbody');\n"
                + "      tbody.innerHTML = (pages || []).map(p => `<tr><td>${p.path}</td><td>${p.title}</td><td>${p.template}</td><td><span style=\"color:${p.eligible?'#10b981':'#ef4444'}\">${p.eligible?'YES':'NO'}</span></td></tr>`).join('');\n"
                + "    }\n"
                + "\n"
                + "    function renderComponentsTable(components) {\n"
                + "      const tbody = document.querySelector('#table-components tbody');\n"
                + "      tbody.innerHTML = (components || []).map(c => `<tr><td>${c.resourceType}</td><td>${c.title}</td><td>${c.group}</td><td><b>${c.proposedEdsBlock || '-'}</b></td><td>${c.capabilityClassification || 'SUPPORTED'}</td></tr>`).join('');\n"
                + "    }\n"
                + "\n"
                + "    function renderRedirectsTable(list) {\n"
                + "      const tbody = document.querySelector('#table-redirects tbody');\n"
                + "      tbody.innerHTML = (list || []).map(r => `<tr><td>${r.sourceUrl}</td><td>${r.targetUrl}</td><td>${r.statusCode}</td><td>${r.conflict ? '⚠️ Conflict' : 'OK'}</td></tr>`).join('') || '<tr><td colspan=\"4\">None</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderDependenciesTable(list) {\n"
                + "      const tbody = document.querySelector('#table-dependencies tbody');\n"
                + "      tbody.innerHTML = (list || []).map(d => `<tr><td>${d.source}</td><td>${d.target}</td><td>${d.edgeType}</td><td>${d.impactLevel}</td></tr>`).join('') || '<tr><td colspan=\"4\">None</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderRolloutTable(list) {\n"
                + "      const tbody = document.querySelector('#table-rollout tbody');\n"
                + "      tbody.innerHTML = (list || []).map(s => `<tr><td>${s.stageIndex}</td><td>${s.stageName}</td><td>${s.targetTrafficPercent}%</td><td>${s.status}</td></tr>`).join('') || '<tr><td colspan=\"4\">None</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderRepairsTable(list) {\n"
                + "      const tbody = document.querySelector('#table-repairs tbody');\n"
                + "      tbody.innerHTML = (list || []).map(r => `<tr><td>${r.targetPath}</td><td>#${r.attemptNumber}</td><td>${r.issueCategory || 'STYLE'}</td><td>${r.successful ? '✅ Fixed' : '❌ Failed'}</td></tr>`).join('') || '<tr><td colspan=\"4\">None</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    function renderBenchmarksTable(list) {\n"
                + "      const tbody = document.querySelector('#table-benchmarks tbody');\n"
                + "      tbody.innerHTML = (list || []).map(b => `<tr><td>${b.agent}</td><td>${b.operation}</td><td>${b.durationMs}ms</td><td>${b.costMicros.toFixed(1)}</td></tr>`).join('') || '<tr><td colspan=\"4\">None</td></tr>';\n"
                + "    }\n"
                + "\n"
                + "    // Auto check projects on load\n"
                + "    window.addEventListener('load', async () => {\n"
                + "      try {\n"
                + "        const projects = await api('projects');\n"
                + "        if (projects && projects.length > 0) {\n"
                + "          currentProjectId = projects[0].id;\n"
                + "          document.getElementById('btn-dryrun').disabled = false;\n"
                + "          await refreshDashboard();\n"
                + "        }\n"
                + "      } catch (e) {\n"
                + "        console.log('Project check:', e);\n"
                + "      }\n"
                + "    });\n"
                + "  </script>\n"
                + "</body>\n"
                + "</html>\n";
    }
}
