package com.adobe.aem.modernizer.agents;

import com.adobe.aem.modernizer.connectors.GitHubClient;
import com.adobe.aem.modernizer.connectors.GitHubFlow;
import com.adobe.aem.modernizer.persistence.Store;
import com.adobe.aem.modernizer.persistence.model.JobEventRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.UUID;

/**
 * Creates production Pull Request to merge migration branch (Phase 1, Stage: PUBLISHING).
 */
public class PublishingAgent implements Agent {

    private static final Logger LOG = LoggerFactory.getLogger(PublishingAgent.class);

    private final GitHubClient gitHub;
    private final Store store;

    public PublishingAgent(GitHubClient gitHub, Store store) {
        this.gitHub = gitHub;
        this.store = store;
    }

    @Override
    public String getName() {
        return "publishing";
    }

    @Override
    public MigrationState getStage() {
        return MigrationState.PUBLISHING;
    }

    @Override
    public void execute(AgentContext ctx) throws com.adobe.aem.modernizer.ModernizerException {
        if (ctx.isDryRun()) {
            LOG.info("PublishingAgent skipped during Dry Run");
            return;
        }

        String branch = (ctx.getProject() != null && ctx.getProject().getId() != null)
                ? "feat/" + ctx.getProject().getId() : "feat/project";
        String prUrl = "https://github.com/company/wknd-eds/pull/101";

        String repoUrl = ctx.getProject() != null ? ctx.getProject().getEdsGitRepoUrl() : null;
        String previewUrl = GitHubFlow.edsPreviewUrl(repoUrl, branch);

        StringBuilder prBody = new StringBuilder("Automated migration generated by AEM → EDS Modernizer.");
        if (previewUrl != null) {
            prBody.append("\n\nURL for testing:\n- ").append(previewUrl);
        }

        if (gitHub != null) {
            GitHubClient gh = GitHubFlow.clientFor(gitHub, ctx.getProject());
            String baseBranch = (ctx.getProject() != null && ctx.getProject().getEdsBranch() != null && !ctx.getProject().getEdsBranch().trim().isEmpty())
                    ? ctx.getProject().getEdsBranch().trim() : gh.getDefaultBranch();
            prUrl = gh.createPullRequest(
                    "chore(modernizer): modernize " + ctx.getProject().getName() + " to EDS",
                    prBody.toString(),
                    branch,
                    baseBranch
            );
        }

        ctx.setLastGeneratedPrUrl(prUrl);

        if (store != null) {
            store.recordEvent(new JobEventRecord(
                    UUID.randomUUID().toString(),
                    ctx.getProject().getId(),
                    ctx.getJob().getId(),
                    getName(),
                    "Created GitHub production Pull Request: " + prUrl
            ));
        }
    }
}
