package com.adobe.aem.modernizer.agents;

import com.adobe.aem.modernizer.ai.AiGateway;
import com.adobe.aem.modernizer.connectors.GitHubClient;
import com.adobe.aem.modernizer.persistence.Store;
import com.adobe.aem.modernizer.persistence.model.JobEventRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.UUID;

/**
 * Creates production Pull Request to merge migration branch (Phase 1, Stage: PUBLISHING).
 */
public class PublishingAgent implements Agent {

    private static final Logger LOG = LoggerFactory.getLogger(PublishingAgent.class);

    private final GitHubClient gitHub;
    private final Store store;
    private final AiGateway ai;

    public PublishingAgent(GitHubClient gitHub, Store store, AiGateway ai) {
        this.gitHub = gitHub;
        this.store = store;
        this.ai = ai;
    }

    @Override
    public String getName() {
        return "publishing";
    }

    @Override
    public MigrationState getStage() {
        return MigrationState.PUBLISHING;
    }

    @Override
    public void execute(AgentContext ctx) throws com.adobe.aem.modernizer.ModernizerException {
        if (ctx.isDryRun()) {
            LOG.info("PublishingAgent skipped during Dry Run");
            return;
        }

        String branch = "modernizer/" + ctx.getProject().getId() + "/" + ctx.getJob().getId();
        String prUrl = "https://github.com/company/wknd-eds/pull/101";

        if (gitHub != null) {
            prUrl = gitHub.createPullRequest(
                    "chore(modernizer): modernize " + ctx.getProject().getName() + " to EDS",
                    "Automated migration generated by AEM → EDS Modernizer.",
                    branch,
                    "main"
            );
        }

        ctx.setLastGeneratedPrUrl(prUrl);

        if (store != null) {
            store.recordEvent(new JobEventRecord(
                    UUID.randomUUID().toString(),
                    ctx.getProject().getId(),
                    ctx.getJob().getId(),
                    getName(),
                    "Created GitHub production Pull Request: " + prUrl
            ));
        }
    }
}
